// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef X509_EXTENSION_BUILDER_DICE_TCBINFO_H_
#define X509_EXTENSION_BUILDER_DICE_TCBINFO_H_

#include "asn1/x509_extension_builder.h"
#include "riot/tcg_dice.h"


/**
 * Builder for the TCG DICE TcbInfo extension.  The extension builder does not rely on any external
 * components or libraries.
 */
struct x509_extension_builder_dice_tcbinfo {
	struct x509_extension_builder base;		/**< Base extension builder API. */
	const struct tcg_dice_tcbinfo *tcb;		/**< The TCB information to encode in the extension. */
	uint8_t *ext_buffer;					/**< Buffer to use for building the extension data. */
	size_t ext_length;						/**< Length of th extension data duffer. */
};


int x509_extension_builder_dice_tcbinfo_init (struct x509_extension_builder_dice_tcbinfo *builder,
	const struct tcg_dice_tcbinfo *tcb);
int x509_extension_builder_dice_tcbinfo_init_with_buffer (
	struct x509_extension_builder_dice_tcbinfo *builder, const struct tcg_dice_tcbinfo *tcb,
	uint8_t *ext_buffer, size_t buffer_length);
void x509_extension_builder_dice_tcbinfo_release (
	const struct x509_extension_builder_dice_tcbinfo *builder);


/* Internal definitions for use by Ueid extension builders. */
extern const uint8_t X509_EXTENSION_BUILDER_DICE_TCBINFO_OID[];

/**
 * Length of the encoded TCG DICE Ueid extension OID.
 */
#define	X509_EXTENSION_BUILDER_DICE_TCBINFO_OID_LENGTH		6


#define	DICE_TCBINFO_EXTENSION_ERROR(code)		ROT_ERROR (ROT_MODULE_DICE_TCBINFO_EXTENSION, code)

/**
 * Error codes that can be generated by a TCG DICE Ueid extension builder.
 */
enum {
	DICE_TCBINFO_EXTENSION_INVALID_ARGUMENT = DICE_TCBINFO_EXTENSION_ERROR (0x00),	/**< Input parameter is null or not valid. */
	DICE_TCBINFO_EXTENSION_NO_MEMORY = DICE_TCBINFO_EXTENSION_ERROR (0x01),			/**< Memory allocation failed. */
	DICE_TCBINFO_EXTENSION_SMALL_EXT_BUFFER = DICE_TCBINFO_EXTENSION_ERROR (0x02),	/**< The extension buffer is too small for the data. */
	DICE_TCBINFO_EXTENSION_UNKNOWN_FWID = DICE_TCBINFO_EXTENSION_ERROR (0x03),		/**< The FWID digest is an unknown type. */
	DICE_TCBINFO_EXTENSION_NO_FWID = DICE_TCBINFO_EXTENSION_ERROR (0x04),			/**< No FWID digest was provided in the TCB info. */
	DICE_TCBINFO_EXTENSION_NO_VERSION = DICE_TCBINFO_EXTENSION_ERROR (0x05),		/**< No version was provided in the TCB info. */
};


#endif /* X509_EXTENSION_BUILDER_DICE_TCBINFO_H_ */
