// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef DME_STRUCTURE_TESTING_H_
#define DME_STRUCTURE_TESTING_H_

#include <stdint.h>
#include <stddef.h>
#include "asn1/dme/dme_structure.h"


extern const uint8_t DME_STRUCTURE_TESTING_OID_TYPE[];
extern const size_t DME_STRUCTURE_TESTING_OID_TYPE_LEN;

extern const uint8_t DME_STRUCTURE_TESTING_DATA[];
extern const size_t DME_STRUCTURE_TESTING_DATA_LEN;

extern const uint8_t DME_STRUCTURE_TESTING_OID_SIG_ECC_SHA256[];
extern const size_t DME_STRUCTURE_TESTING_OID_SIG_ECC_SHA256_LEN;

extern const uint8_t DME_STRUCTURE_TESTING_SIG_ECC256_SHA256[];
extern const size_t DME_STRUCTURE_TESTING_SIG_ECC256_SHA256_LEN;

extern const uint8_t DME_STRUCTURE_TESTING_OID_SIG_ECC_SHA384[];
extern const size_t DME_STRUCTURE_TESTING_OID_SIG_ECC_SHA384_LEN;

extern const uint8_t DME_STRUCTURE_TESTING_SIG_ECC384_SHA384[];
extern const size_t DME_STRUCTURE_TESTING_SIG_ECC384_SHA384_LEN;

extern const uint8_t DME_STRUCTURE_TESTING_OID_SIG_ECC_SHA512[];
extern const size_t DME_STRUCTURE_TESTING_OID_SIG_ECC_SHA512_LEN;

extern const uint8_t DME_STRUCTURE_TESTING_SIG_ECC521_SHA512[];
extern const size_t DME_STRUCTURE_TESTING_SIG_ECC521_SHA512_LEN;

extern const uint8_t DME_STRUCTURE_TESTING_RENEWAL_COUNTER[];
extern const size_t DME_STRUCTURE_TESTING_RENEWAL_COUNTER_LEN;

extern const uint8_t DME_STRUCTURE_TESTING_TYPE1_OID[];
extern const size_t DME_STRUCTURE_TESTING_TYPE1_OID_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE1_DATA[];
extern const size_t DME_STRUCTURE_TESTING_TYPE1_DATA_LEN;

extern const uint8_t DME_STRUCTURE_TESTING_TYPE1_SIG_ECC256_SHA256[];
extern const size_t DME_STRUCTURE_TESTING_TYPE1_SIG_ECC256_SHA256_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE1_SIG_ECC256_SHA256_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE1_SIG_ECC256_SHA256_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE1_SIG_ECC384_SHA384[];
extern const size_t DME_STRUCTURE_TESTING_TYPE1_SIG_ECC384_SHA384_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE1_SIG_ECC384_SHA384_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE1_SIG_ECC384_SHA384_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE1_SIG_ECC521_SHA512[];
extern const size_t DME_STRUCTURE_TESTING_TYPE1_SIG_ECC521_SHA512_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE1_SIG_ECC521_SHA512_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE1_SIG_ECC521_SHA512_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE2_OID[];
extern const size_t DME_STRUCTURE_TESTING_TYPE2_OID_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE2_DATA[];
extern const size_t DME_STRUCTURE_TESTING_TYPE2_DATA_LEN;

extern const uint8_t DME_STRUCTURE_TESTING_TYPE2_SIG_ECC256_SHA256[];
extern const size_t DME_STRUCTURE_TESTING_TYPE2_SIG_ECC256_SHA256_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE2_SIG_ECC256_SHA256_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE2_SIG_ECC256_SHA256_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE2_SIG_ECC384_SHA384[];
extern const size_t DME_STRUCTURE_TESTING_TYPE2_SIG_ECC384_SHA384_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE2_SIG_ECC384_SHA384_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE2_SIG_ECC384_SHA384_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE2_SIG_ECC521_SHA512[];
extern const size_t DME_STRUCTURE_TESTING_TYPE2_SIG_ECC521_SHA512_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE2_SIG_ECC521_SHA512_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE2_SIG_ECC521_SHA512_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE3_OID[];
extern const size_t DME_STRUCTURE_TESTING_TYPE3_OID_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE3_DATA[];
extern const size_t DME_STRUCTURE_TESTING_TYPE3_DATA_LEN;

extern const uint8_t DME_STRUCTURE_TESTING_TYPE3_SIG_ECC256_SHA256[];
extern const size_t DME_STRUCTURE_TESTING_TYPE3_SIG_ECC256_SHA256_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE3_SIG_ECC256_SHA256_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE3_SIG_ECC256_SHA256_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE3_SIG_ECC384_SHA384[];
extern const size_t DME_STRUCTURE_TESTING_TYPE3_SIG_ECC384_SHA384_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE3_SIG_ECC384_SHA384_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE3_SIG_ECC384_SHA384_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE3_SIG_ECC521_SHA512[];
extern const size_t DME_STRUCTURE_TESTING_TYPE3_SIG_ECC521_SHA512_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE3_SIG_ECC521_SHA512_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE3_SIG_ECC521_SHA512_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE4_OID[];
extern const size_t DME_STRUCTURE_TESTING_TYPE4_OID_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE4_DATA[];
extern const size_t DME_STRUCTURE_TESTING_TYPE4_DATA_LEN;

extern const uint8_t DME_STRUCTURE_TESTING_TYPE4_SIG_ECC256_SHA256[];
extern const size_t DME_STRUCTURE_TESTING_TYPE4_SIG_ECC256_SHA256_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE4_SIG_ECC256_SHA256_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE4_SIG_ECC256_SHA256_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE4_SIG_ECC384_SHA384[];
extern const size_t DME_STRUCTURE_TESTING_TYPE4_SIG_ECC384_SHA384_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE4_SIG_ECC384_SHA384_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE4_SIG_ECC384_SHA384_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE4_SIG_ECC521_SHA512[];
extern const size_t DME_STRUCTURE_TESTING_TYPE4_SIG_ECC521_SHA512_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE4_SIG_ECC521_SHA512_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE4_SIG_ECC521_SHA512_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE5_OID[];
extern const size_t DME_STRUCTURE_TESTING_TYPE5_OID_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE5_DATA[];
extern const size_t DME_STRUCTURE_TESTING_TYPE5_DATA_LEN;

extern const uint8_t DME_STRUCTURE_TESTING_TYPE5_SIG_ECC256_SHA256[];
extern const size_t DME_STRUCTURE_TESTING_TYPE5_SIG_ECC256_SHA256_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE5_SIG_ECC256_SHA256_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE5_SIG_ECC256_SHA256_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE5_SIG_ECC384_SHA384[];
extern const size_t DME_STRUCTURE_TESTING_TYPE5_SIG_ECC384_SHA384_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE5_SIG_ECC384_SHA384_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE5_SIG_ECC384_SHA384_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE5_SIG_ECC521_SHA512[];
extern const size_t DME_STRUCTURE_TESTING_TYPE5_SIG_ECC521_SHA512_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE5_SIG_ECC521_SHA512_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE5_SIG_ECC521_SHA512_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE6_OID[];
extern const size_t DME_STRUCTURE_TESTING_TYPE6_OID_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE6_DATA[];
extern const size_t DME_STRUCTURE_TESTING_TYPE6_DATA_LEN;

extern const uint8_t DME_STRUCTURE_TESTING_TYPE6_SIG_ECC256_SHA256[];
extern const size_t DME_STRUCTURE_TESTING_TYPE6_SIG_ECC256_SHA256_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE6_SIG_ECC256_SHA256_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE6_SIG_ECC256_SHA256_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE6_SIG_ECC384_SHA384[];
extern const size_t DME_STRUCTURE_TESTING_TYPE6_SIG_ECC384_SHA384_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE6_SIG_ECC384_SHA384_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE6_SIG_ECC384_SHA384_RAW_S[];

extern const uint8_t DME_STRUCTURE_TESTING_TYPE6_SIG_ECC521_SHA512[];
extern const size_t DME_STRUCTURE_TESTING_TYPE6_SIG_ECC521_SHA512_LEN;
extern const uint8_t DME_STRUCTURE_TESTING_TYPE6_SIG_ECC521_SHA512_RAW_R[];
extern const uint8_t DME_STRUCTURE_TESTING_TYPE6_SIG_ECC521_SHA512_RAW_S[];


void dme_structure_testing_structure_ecc384_sha384 (struct dme_structure *dme);
void dme_structure_testing_structure_no_device_oid (struct dme_structure *dme);
void dme_structure_testing_structure_no_renewal (struct dme_structure *dme);
void dme_structure_testing_structure_ecc256_sha256 (struct dme_structure *dme);
void dme_structure_testing_structure_ecc521_sha512 (struct dme_structure *dme);


#endif /* DME_STRUCTURE_TESTING_H_ */
