// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef TDISP_DRIVER_OBSERVER_H_
#define TDISP_DRIVER_OBSERVER_H_

#include "status/module_id.h"


/**
 * Interface for notifying observers of TDISP driver events.  Unwanted event notifications will be
 * set to null.
 */
struct tdisp_driver_observer {
	/**
	 * Notification that a new TDISP interface has been started.
	 *
	 * Arguments passed with the notification will never be null.
	 *
	 * @param observer The observer instance being notified.
	 * @param function_index The function index of the TDISP interface that was
	 * started.
	 */
	void (*on_start_interface) (const struct tdisp_driver_observer *observer,
		uint32_t *function_index);

	/**
	 * Notification that a TDISP interface has been stopped.
	 *
	 * Arguments passed with the notification will never be null.
	 *
	 * @param observer The observer instance being notified.
	 * @param function_index The function index of the TDISP interface that was
	 * stopped.
	 */
	void (*on_stop_interface) (const struct tdisp_driver_observer *observer,
		uint32_t *function_index);
};


#define	TDISP_DRIVER_OBSERVER_ERROR(code)	ROT_ERROR (ROT_MODULE_TDISP_DRIVER_OBSERVER, code)

/**
 * Error codes that can be generated by a TDISP driver observer.
 */
enum {
	TDISP_DRIVER_OBSERVER_INVALID_ARGUMENT = TDISP_DRIVER_OBSERVER_ERROR (0x00),	/**< Input parameter is null or not valid. */
	TDISP_DRIVER_OBSERVER_NO_MEMORY = TDISP_DRIVER_OBSERVER_ERROR (0x01),			/**< Memory allocation failed. */
};


#endif	/* TDISP_DRIVER_OBSERVER_H_ */
