// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef SPDM_PERSISTENT_CONTEXT_INTERFACE_H_
#define SPDM_PERSISTENT_CONTEXT_INTERFACE_H_

#include "status/rot_status.h"

/**
 * Forward declaration for the spdm_responder_state structure.
 */
struct spdm_responder_state;

/**
 * Forward declaration for the spdm_persistent_context structure.
 */
struct spdm_secure_session_manager_persistent_state;

/**
 * Structure to provide an interface for managing the persistent context of SPDM.
 */
struct spdm_persistent_context_interface {
	/**
	 * Get the SPDM responder state. This call will map required memory to provide access to
	 * persistent state location. The caller must call unlock() to release this mapping.
	 * The state pointer will remain valid until unlock() is called. After unlock called it
	 * should not be used anymore.
	 *
	 * @param context Context for managing persistent SPDM state.
	 * @param state Output pointer to the responder state.
	 *
	 * @return 0 if the responder state is retrieved successfully, error code otherwise.
	 */
	int (*get_responder_state) (const struct spdm_persistent_context_interface *context,
		struct spdm_responder_state **state);

	/**
	 * Get the SPDM secure session manager persistent state. This call will lock necessary resources to access
	 * the persistent state. The caller must call unlock() to release the resources. The state pointer
	 * will remain valid until unlock() is called. After unlock called it should not be used anymore.
	 *
	 * @param context Context for managing persistent SPDM state.
	 * @param state Output pointer to the secure session manager persistent state.
	 *
	 * @return 0 if the secure session manager state is retrieved successfully, error code otherwise.
	 */
	int (*get_secure_session_manager_state) (
		const struct spdm_persistent_context_interface *context,
		struct spdm_secure_session_manager_persistent_state **state);

	/**
	 * Releases state resource pointer which was obtained by get_* call. For each get_* call that
	 * returns successfully, the caller must call unlock() to release the resources. The state pointer
	 * will remain valid until unlock() is called.
	 *
	 * @param context Context for managing persistent SPDM state.
	 */
	void (*unlock) (const struct spdm_persistent_context_interface *context);
};

#define	SPDM_PERSISTENT_CONTEXT_ERROR(code)		ROT_ERROR (ROT_MODULE_SPDM_PERSISTENT_CONTEXT, code)

/**
 * Error codes that can be generated by a SPDM persistent context.
 */
enum {
	SPDM_PERSISTENT_CONTEXT_INVALID_ARGUMENT = SPDM_PERSISTENT_CONTEXT_ERROR (0x00),					/**< Input parameter is null or not valid. */
	SPDM_PERSISTENT_CONTEXT_NO_MEMORY = SPDM_PERSISTENT_CONTEXT_ERROR (0x01),							/**< Memory allocation failed. */
	SPDM_PERSISTENT_CONTEXT_GET_RESPONDER_STATE_FAILED = SPDM_PERSISTENT_CONTEXT_ERROR (0x02),			/**< Failed to get the responder state. */
	SPDM_PERSISTENT_CONTEXT_GET_SESSION_MANAGER_STATE_FAILED = SPDM_PERSISTENT_CONTEXT_ERROR (0x03),	/**< Failed to get the secure session manager state. */
};


#endif	/* SPDM_PERSISTENT_CONTEXT_INTERFACE_H_ */
