// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef SPDM_PROTOCOL_SESSION_OBSERVER_H_
#define SPDM_PROTOCOL_SESSION_OBSERVER_H_

#include "status/rot_status.h"


/**
 * Interface for notifying observers of SPDM session events.  Unwanted event notifications
 * will be set to null.
 */
struct spdm_protocol_session_observer {
	/**
	 * Notification that a new SPDM session has been established.
	 *
	 * Arguments passed with the notification will never be null.
	 *
	 * @param observer The observer instance being notified.
	 * @param session_id The session ID of the new SPDM session.
	 */
	void (*on_new_session) (const struct spdm_protocol_session_observer *observer,
		uint32_t *session_id);

	/**
	 * Notification that an SPDM session has been closed.
	 *
	 * Arguments passed with the notification will never be null.
	 *
	 * @param observer The observer instance being notified.
	 * @param session_id The session ID of the closed SPDM session.
	 */
	void (*on_close_session) (const struct spdm_protocol_session_observer *observer,
		uint32_t *session_id);
};


#define	SPDM_PROTOCOL_SESSION_OBSERVER_ERROR(code)     \
	ROT_ERROR (ROT_MODULE_SPDM_PROTOCOL_SESSION_OBSERVER, code)

/**
 * Error codes that can be generated by a SPDM observer.
 */
enum {
	SPDM_PROTOCOL_SESSION_OBSERVER_INVALID_ARGUMENT = SPDM_PROTOCOL_SESSION_OBSERVER_ERROR (0x00),	/**< Input parameter is null or not valid. */
	SPDM_PROTOCOL_SESSION_OBSERVER_NO_MEMORY = SPDM_PROTOCOL_SESSION_OBSERVER_ERROR (0x01),			/**< Memory allocation failed. */
};


#endif	/* SPDM_PROTOCOL_SESSION_OBSERVER_H_ */
