// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef SPDM_CERTIFICATE_CHAIN_H_
#define SPDM_CERTIFICATE_CHAIN_H_

#include <stddef.h>
#include <stdint.h>
#include "platform_api.h"
#include "crypto/ecc.h"
#include "crypto/hash.h"
#include "status/rot_status.h"


#pragma pack(push, 1)

/**
 * Constant length header on an SPDM certificate chain indicating the length of the data.
 */
struct PLATFORM_LITTLE_ENDIAN_STORAGE spdm_certificate_chain_min_header {
	uint16_t length;	/**< Total length of the cert chain, including the header. */
	uint16_t reserved;	/**< Reserved */
};

/**
 * Header that is prepended to every cert chain reported by SPDM.  The header is variable length
 * depending on the length of the root CA digest.  This length is determined by the negotiated hash
 * algorithm used by the connection.  Immediately following the header is the catenation of all the
 * DER-encoded certificates in the chain.
 */
struct spdm_certificate_chain_header {
	struct spdm_certificate_chain_min_header min_hdr;	/**< Constant length header on the certificate chain. */
	uint8_t root_hash[HASH_MAX_HASH_LEN];				/**< Digest of the root CA certificate.  Reserving the worst-case length. */
};

#pragma pack(pop)


/**
 * Manages a single certificate chain available via SPDM.  This translates to a single certificate
 * slot.
 */
struct spdm_certificate_chain {
	/**
	 * Calculate the digest for the full certificate chain.
	 *
	 * @param chain The certificate chain that should be hashed.
	 * @param hash The hash engine to use for calculating the digest.
	 * @param hash_type The hash algorithm to use.  This will determine the amount of data this is
	 * generated.
	 * @param digest Output for the digest of the certificate chain.
	 * @param length The length of the output buffer.
	 *
	 * @return 0 if the digest was calculated successfully or an error code.
	 */
	int (*get_digest) (const struct spdm_certificate_chain *chain, const struct hash_engine *hash,
		enum hash_type hash_type, uint8_t *digest, size_t length);

	/**
	 * Retrieve the full certificate chain in the structure required by SPDM.
	 *
	 * @param chain The certificate chain to retrieve.
	 * @param hash The hash engine to use for calculating the root CA digest.
	 * @param root_ca_hash The hash algorithm to run when calculating the root CA digest.
	 * @param offset Byte offset within the SPDM structure being requested.
	 * @param buffer Output for the requested certificate chain.
	 * @param length Length of the output buffer, representing the maximum amount of certificate
	 * data to retrieve.  On successful completion, this will be updated to reflect the actual
	 * amount of data written to the buffer.
	 * @param total_length Output for the total length of the certificate chain.  This value is not
	 * adjusted based on the provided offset.  It always provides the length of the entire
	 * certificate chain.
	 *
	 * @return 0 if the certificate chain was retrieved successfully or an error code.
	 */
	int (*get_certificate_chain) (const struct spdm_certificate_chain *chain,
		const struct hash_engine *hash, enum hash_type root_ca_hash, size_t offset, uint8_t *buffer,
		size_t *length, size_t *total_length);

	/**
	 * Generate an ECDSA signature for a given message using the private key associated with the
	 * leaf certificate of the chain.
	 *
	 * @param chain The certificate chain to use for signing.
	 * @param ecc The ECC engine to use for signature generation.
	 * @param hash The hash engine that will be used to calculate the message digest.
	 * @param hash_algo Algorithm to use for message hashing.
	 * @param message The raw message data that should be signed.
	 * @param msg_length Length of the message.
	 * @param signature Output buffer for the ECDSA signature.  The signature will be DER encoded.
	 * @param sig_length The length of the signature output buffer.
	 *
	 * @return The length of the signature or an error code.  Use ROT_IS_ERROR to check the return
	 * value.
	 */
	int (*sign_message) (const struct spdm_certificate_chain *chain, const struct ecc_engine *ecc,
		const struct hash_engine *hash, enum hash_type hash_algo, const uint8_t *message,
		size_t msg_length, uint8_t *signature, size_t sig_length);
};


#define	SPDM_CERT_CHAIN_ERROR(code)		ROT_ERROR (ROT_MODULE_SPDM_CERT_CHAIN, code)

/**
 * Error codes that can be generated by a SPDM certificate chain manager.
 */
enum {
	SPDM_CERT_CHAIN_INVALID_ARGUMENT = SPDM_CERT_CHAIN_ERROR (0x00),	/**< Input parameter is null or not valid. */
	SPDM_CERT_CHAIN_NO_MEMORY = SPDM_CERT_CHAIN_ERROR (0x01),			/**< Memory allocation failed. */
	SPDM_CERT_CHAIN_GET_DIGEST_FAILED = SPDM_CERT_CHAIN_ERROR (0x02),	/**< Failed to calculate the certificate chain digest. */
	SPDM_CERT_CHAIN_GET_CHAIN_FAILED = SPDM_CERT_CHAIN_ERROR (0x03),	/**< Failed to retrieve the certificate chain. */
	SPDM_CERT_CHAIN_SIGN_MSG_FAILED = SPDM_CERT_CHAIN_ERROR (0x04),		/**< Failed to sign using the certificate chain. */
	SPDM_CERT_CHAIN_MISSING_CERT = SPDM_CERT_CHAIN_ERROR (0x05),		/**< A required cert is not available. */
};


#endif	/* SPDM_CERTIFICATE_CHAIN_H_ */
