// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef PCR_H_
#define PCR_H_

#include <stdint.h>
#include <stdbool.h>
#include "platform.h"
#include "crypto/hash.h"
#include "pcr_data.h"


#define PCR_DIGEST_LENGTH 	SHA256_HASH_LENGTH


/**
 * Container for a PCR measurement
 */
struct pcr_measurement {
	uint8_t digest[PCR_DIGEST_LENGTH];						/**< Digest buffer */
	uint8_t measurement[PCR_DIGEST_LENGTH];					/**< Aggregated measurement buffer */
	struct pcr_measured_data *measured_data;				/**< Raw data used for measurement */
	uint32_t event_type;									/**< TCG event type */
};

/**
 * List of measurements to be aggregated in a PCR
 */
struct pcr_bank {
	struct pcr_measurement *measurement_list;				/**< List of measurements */
	size_t num_measurements;								/**< Number of measurements */
	bool explicit;											/**< PCR bank contains an explicit measurement. */
	platform_mutex lock;									/**< Synchronization lock */
};


int pcr_init (struct pcr_bank *pcr, uint8_t pcr_num_measurements);
void pcr_release (struct pcr_bank *pcr);

int pcr_check_measurement_index (struct pcr_bank *pcr, uint8_t measurement_index);

int pcr_update_digest (struct pcr_bank *pcr, uint8_t measurement_index, const uint8_t *digest,
	size_t digest_len);
int pcr_update_buffer (struct pcr_bank *pcr, struct hash_engine *hash, uint8_t measurement_index,
	const uint8_t *buf, size_t buf_len);
int pcr_update_event_type (struct pcr_bank *pcr, uint8_t measurement_index, uint32_t event_type);

int pcr_compute (struct pcr_bank *pcr, struct hash_engine *hash, uint8_t *measurement, bool lock);
int pcr_get_measurement (struct pcr_bank *pcr, uint8_t measurement_index,
	struct pcr_measurement *measurement);
int pcr_get_all_measurements (struct pcr_bank *pcr, const uint8_t **measurement_list);
int pcr_get_num_measurements (struct pcr_bank *pcr);
int pcr_invalidate_measurement_index (struct pcr_bank *pcr, uint8_t measurement_index);

int pcr_set_measurement_data (struct pcr_bank *pcr, uint8_t measurement_index,
	struct pcr_measured_data *measurement_data);
int pcr_get_measurement_data (struct pcr_bank *pcr, uint8_t measurement_index, size_t offset,
	uint8_t *buffer, size_t length);

int pcr_lock (struct pcr_bank *pcr);
int pcr_unlock (struct pcr_bank *pcr);


#define	PCR_ERROR(code)		ROT_ERROR (ROT_MODULE_PCR, code)

/**
 * Error codes that can be generated by the PCR management module.
 */
enum {
	PCR_INVALID_ARGUMENT = PCR_ERROR (0x00),						/**< Input parameter is null or not valid. */
	PCR_NO_MEMORY = PCR_ERROR (0x01),								/**< Memory allocation failed. */
	PCR_UNSUPPORTED_ALGO = PCR_ERROR (0x02),						/**< Unsupported hashing algorithm. */
	PCR_INVALID_PCR = PCR_ERROR (0x03),								/**< Invalid PCR bank. */
	PCR_INVALID_TYPE = PCR_ERROR (0x04),							/**< Invalid measurement type. */
	PCR_INVALID_INDEX = PCR_ERROR (0x05),							/**< Invalid measurement index. */
	PCR_INVALID_DATA_TYPE = PCR_ERROR (0x06),						/**< Invalid PCR measured data type. */
	PCR_MEASURED_DATA_INVALID_MEMORY = PCR_ERROR (0x08),			/**< PCR Measured data memory location is null or invalid */
	PCR_MEASURED_DATA_INVALID_FLASH_DEVICE = PCR_ERROR (0x09),		/**< Flash device storing PCR Measured data is null or invalid */
	PCR_MEASURED_DATA_INVALID_CALLBACK = PCR_ERROR (0x0A),			/**< Callback to retrieve PCR Measured data is null or invalid */
};


#endif //PCR_H_
