// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef AES_TESTING_ENGINE_H_
#define AES_TESTING_ENGINE_H_

#include "testing/platform_aes_testing.h"


/* AES-GCM engine */
#ifndef	AES_TESTING_ENGINE_NAME
#include "crypto/aes_mbedtls.h"
#define	AES_TESTING_ENGINE_NAME	mbedtls
#define	AES_TESTING_ENGINE_STATE_NAME	mbedtls_state
#endif


#define	AES_TESTING_ENGINE_STRUCT_DEF(name)		struct aes_engine_ ## name
#define	AES_TESTING_ENGINE_STRUCT(name)			AES_TESTING_ENGINE_STRUCT_DEF(name)
#define	AES_TESTING_ENGINE						AES_TESTING_ENGINE_STRUCT(AES_TESTING_ENGINE_NAME)
#define	AES_TESTING_ENGINE_STATE                \
	AES_TESTING_ENGINE_STRUCT(AES_TESTING_ENGINE_STATE_NAME)

#define	AES_TESTING_ENGINE_INIT_FUNC_DEF(name)	aes_ ## name ## _init
#define	AES_TESTING_ENGINE_INIT_FUNC(name)		AES_TESTING_ENGINE_INIT_FUNC_DEF(name)
#define	AES_TESTING_ENGINE_INIT                 \
	AES_TESTING_ENGINE_INIT_FUNC(AES_TESTING_ENGINE_NAME)

#define	AES_TESTING_ENGINE_RELEASE_FUNC_DEF(name)	aes_ ## name ## _release
#define	AES_TESTING_ENGINE_RELEASE_FUNC(name)		AES_TESTING_ENGINE_RELEASE_FUNC_DEF(name)
#define	AES_TESTING_ENGINE_RELEASE                  \
	AES_TESTING_ENGINE_RELEASE_FUNC(AES_TESTING_ENGINE_NAME)


/* AES-XTS engine */
#ifndef	AES_XTS_TESTING_ENGINE_NAME
#include "crypto/aes_xts_mbedtls.h"
#define	AES_XTS_TESTING_ENGINE_NAME	mbedtls
#define	AES_XTS_TESTING_ENGINE_STATE_NAME	mbedtls_state
#endif


#define	AES_XTS_TESTING_ENGINE_STRUCT_DEF(name)		struct aes_xts_engine_ ## name
#define	AES_XTS_TESTING_ENGINE_STRUCT(name)			AES_XTS_TESTING_ENGINE_STRUCT_DEF(name)
#define	AES_XTS_TESTING_ENGINE                      \
	AES_XTS_TESTING_ENGINE_STRUCT(AES_XTS_TESTING_ENGINE_NAME)
#define	AES_XTS_TESTING_ENGINE_STATE                \
	AES_XTS_TESTING_ENGINE_STRUCT(AES_XTS_TESTING_ENGINE_STATE_NAME)

#define	AES_XTS_TESTING_ENGINE_INIT_FUNC_DEF(name)	aes_xts_ ## name ## _init
#define	AES_XTS_TESTING_ENGINE_INIT_FUNC(name)		AES_XTS_TESTING_ENGINE_INIT_FUNC_DEF(name)
#define	AES_XTS_TESTING_ENGINE_INIT                 \
	AES_XTS_TESTING_ENGINE_INIT_FUNC(AES_XTS_TESTING_ENGINE_NAME)

#define	AES_XTS_TESTING_ENGINE_RELEASE_FUNC_DEF(name)	aes_xts_ ## name ## _release
#define	AES_XTS_TESTING_ENGINE_RELEASE_FUNC(name)       \
	AES_XTS_TESTING_ENGINE_RELEASE_FUNC_DEF(name)
#define	AES_XTS_TESTING_ENGINE_RELEASE                  \
	AES_XTS_TESTING_ENGINE_RELEASE_FUNC(AES_XTS_TESTING_ENGINE_NAME)


#endif	/* AES_TESTING_ENGINE_H_ */
