// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef AES_CBC_H_
#define AES_CBC_H_

#include <stddef.h>
#include <stdint.h>
#include "status/rot_status.h"


/**
 * Block size for AES-CBC operations.  All data lengths must be whole number multiples of this
 * value.
 */
#define	AES_CBC_BLOCK_SIZE			16

/**
 * The length of an AES 256 key for CBC operations.
 */
#define	AES_CBC_256_KEY_LENGTH		32


/**
 * A platform-independent API for encrypting data using AES-CBC.  AES-CBC engine instances are not
 * guaranteed to be thread-safe.
 */
struct aes_cbc_engine {
	/**
	 * Set the key to use for AES-CBC operations.  This must be called at least once before any
	 * encryption or decryption operation can be performed, and again if a different key should be
	 * used.
	 *
	 * @param engine The AES-CBC engine to configure.
	 * @param key The encryption key to use.
	 * @param length The length of the encryption key.
	 *
	 * @return 0 if the AES key was configured successfully or an error code.
	 */
	int (*set_key) (const struct aes_cbc_engine *engine, const uint8_t *key, size_t length);

	/**
	 * Erase the key being used for AES-CBC operations.  A new key will need to be set before any
	 * additional encryption operations can be performed.
	 *
	 * @param engine the AES-CBC engine to configure.
	 *
	 * @return 0 if the AES key was cleared successfully or an error code.
	 */
	int (*clear_key) (const struct aes_cbc_engine *engine);

	/**
	 * Encrypt data using AES-CBC mode.  The engine must be provided with a key prior to calling
	 * this function.
	 *
	 * @param engine The AES-CBC engine to use for encryption.
	 * @param plaintext The data to encrypt.
	 * @param length The amount of data to encrypt.  This must be aligned to the AES block size.
	 * @param iv Initialization vector for the encryption operation.
	 * @param ciphertext The buffer to hold the encrypted data.  The ciphertext will be the same
	 * length as the plaintext.  This buffer may be the same as the input plaintext buffer.
	 * @param out_length The size of the output buffer.
	 * @param out_iv Optional output buffer for the IV that would be used to continue the
	 * encryption operation with additional data.  This allows encryption to be executed without
	 * having all the data available in memory at the same time.  This can be the same memory as the
	 * input IV.
	 *
	 * @return 0 if the data was encrypted successfully or an error code.
	 */
	int (*encrypt_data) (const struct aes_cbc_engine *engine, const uint8_t *plaintext,
		size_t length, const uint8_t iv[AES_CBC_BLOCK_SIZE], uint8_t *ciphertext, size_t out_length,
		uint8_t out_iv[AES_CBC_BLOCK_SIZE]);

	/**
	 * Decrypt data using AES-CBC mode.  The engine must be provided with a key prior to calling
	 * this function.
	 *
	 * @param engine The AES-CBC engine to use for decryption.
	 * @param ciphertext The encrypted data to decrypt.
	 * @param length The length of the encrypted data.  This must be aligned to the AES block size.
	 * @param iv Initialization vector for the decryption operation.
	 * @param plaintext The buffer to hold the decrypted data.  The plaintext will be the same
	 * length as the ciphertext.  This buffer may be the same as the input ciphertext buffer.
	 * @param out_length The size of the output buffer.
	 * @param out_iv Optional output buffer for the IV that would be used to continue the
	 * decryption operation with additional data.  This allows decryption to be executed without
	 * having all the data available in memory at the same time.  This can be the same memory as the
	 * input IV.
	 *
	 * @return 0 if the data was decrypted successfully or an error code.
	 */
	int (*decrypt_data) (const struct aes_cbc_engine *engine, const uint8_t *ciphertext,
		size_t length, const uint8_t iv[AES_CBC_BLOCK_SIZE], uint8_t *plaintext, size_t out_length,
		uint8_t out_iv[AES_CBC_BLOCK_SIZE]);
};


#define	AES_CBC_ENGINE_ERROR(code)		ROT_ERROR (ROT_MODULE_AES_CBC_ENGINE, code)

/**
 * Error codes that can be generated by an AES-CBC engine.
 */
enum {
	AES_CBC_ENGINE_INVALID_ARGUMENT = AES_CBC_ENGINE_ERROR (0x00),			/**< Input parameter is null or not valid. */
	AES_CBC_ENGINE_NO_MEMORY = AES_CBC_ENGINE_ERROR (0x01),					/**< Memory allocation failed. */
	AES_CBC_ENGINE_SET_KEY_FAILED = AES_CBC_ENGINE_ERROR (0x02),			/**< The encryption key could not be set. */
	AES_CBC_ENGINE_CLEAR_KEY_FAILED = AES_CBC_ENGINE_ERROR (0x03),			/**< The encryption key could not be cleared. */
	AES_CBC_ENGINE_ENCRYPT_FAILED = AES_CBC_ENGINE_ERROR (0x04),			/**< The ciphertext was not decrypted. */
	AES_CBC_ENGINE_DECRYPT_FAILED = AES_CBC_ENGINE_ERROR (0x05),			/**< The plaintext was not encrypted. */
	AES_CBC_ENGINE_UNSUPPORTED_KEY_LENGTH = AES_CBC_ENGINE_ERROR (0x06),	/**< The encryption key length is not supported by the engine. */
	AES_CBC_ENGINE_INVALID_KEY_LENGTH = AES_CBC_ENGINE_ERROR (0x07),		/**< The key length is not a valid AES-CBC key length. */
	AES_CBC_ENGINE_INVALID_DATA_LENGTH = AES_CBC_ENGINE_ERROR (0x08),		/**< The data length is aligned to the AES block size. */
	AES_CBC_ENGINE_OUT_BUFFER_TOO_SMALL = AES_CBC_ENGINE_ERROR (0x09),		/**< Not enough space in an output buffer provided for the operation. */
	AES_CBC_ENGINE_NO_KEY = AES_CBC_ENGINE_ERROR (0x0a),					/**< No key was set prior to encryption/decryption. */
	AES_CBC_ENGINE_HW_NOT_INIT = AES_CBC_ENGINE_ERROR (0x0b),				/**< The AES hardware has not been initialized. */
	AES_CBC_ENGINE_SELF_TEST_FAILED = AES_CBC_ENGINE_ERROR (0x0c),			/**< An internal self-test of the AES engine failed. */
	AES_CBC_ENGINE_UNSUPPORTED_OPERATION = AES_CBC_ENGINE_ERROR (0x0d),		/**< The requested operation is not supported. */
};


#endif	/* AES_CBC_H_ */
