// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef AES_ECB_H_
#define AES_ECB_H_

#include <stddef.h>
#include <stdint.h>
#include "status/rot_status.h"


/**
 * Block size for AES-ECB operations.  All data lengths must be whole number multiples of this
 * value.
 */
#define	AES_ECB_BLOCK_SIZE			16

/**
 * The length of an AES 256 key for ECB operations.
 */
#define	AES_ECB_256_KEY_LENGTH		32


/**
 * A platform-independent API for encrypting data using AES-ECB.  AES-ECB engine instances are not
 * guaranteed to be thread-safe.
 */
struct aes_ecb_engine {
	/**
	 * Set the key to use for AES-ECB operations.  This must be called at least once before any
	 * encryption or decryption operation can be performed, and again if a different key should be
	 * used.
	 *
	 * @param engine The AES-ECB engine to configure.
	 * @param key The encryption key to use.
	 * @param length The length of the encryption key.
	 *
	 * @return 0 if the AES key was configured successfully or an error code.
	 */
	int (*set_key) (const struct aes_ecb_engine *engine, const uint8_t *key, size_t length);

	/**
	 * Erase the key being used for AES-ECB operations.  A new key will need to be set before any
	 * additional encryption operations can be performed.
	 *
	 * @param engine the AES-ECB engine to configure.
	 *
	 * @return 0 if the AES key was cleared successfully or an error code.
	 */
	int (*clear_key) (const struct aes_ecb_engine *engine);

	/**
	 * Encrypt data using AES-ECB mode.  The engine must be provided with a key prior to calling
	 * this function.
	 *
	 * @param engine The AES-ECB engine to use for encryption.
	 * @param plaintext The data to encrypt.
	 * @param length The amount of data to encrypt.  This must be aligned to the AES block size.
	 * @param ciphertext The buffer to hold the encrypted data.  The ciphertext will be the same
	 * length as the plaintext.  This buffer may be the same as the input plaintext buffer.
	 * @param out_length The size of the output buffer.
	 *
	 * @return 0 if the data was encrypted successfully or an error code.
	 */
	int (*encrypt_data) (const struct aes_ecb_engine *engine, const uint8_t *plaintext,
		size_t length, uint8_t *ciphertext, size_t out_length);

	/**
	 * Decrypt data using AES-ECB mode.  The engine must be provided with a key prior to calling
	 * this function.
	 *
	 * @param engine The AES-ECB engine to use for decryption.
	 * @param ciphertext The encrypted data to decrypt.
	 * @param length The length of the encrypted data.  This must be aligned to the AES block size.
	 * @param plaintext The buffer to hold the decrypted data.  The plaintext will be the same
	 * length as the ciphertext.  This buffer may be the same as the input ciphertext buffer.
	 * @param out_length The size of the output buffer.
	 *
	 * @return 0 if the data was decrypted successfully or an error code.
	 */
	int (*decrypt_data) (const struct aes_ecb_engine *engine, const uint8_t *ciphertext,
		size_t length, uint8_t *plaintext, size_t out_length);
};


#define	AES_ECB_ENGINE_ERROR(code)		ROT_ERROR (ROT_MODULE_AES_ECB_ENGINE, code)

/**
 * Error codes that can be generated by an AES-ECB engine.
 */
enum {
	AES_ECB_ENGINE_INVALID_ARGUMENT = AES_ECB_ENGINE_ERROR (0x00),			/**< Input parameter is null or not valid. */
	AES_ECB_ENGINE_NO_MEMORY = AES_ECB_ENGINE_ERROR (0x01),					/**< Memory allocation failed. */
	AES_ECB_ENGINE_SET_KEY_FAILED = AES_ECB_ENGINE_ERROR (0x02),			/**< The encryption key could not be set. */
	AES_ECB_ENGINE_ENCRYPT_FAILED = AES_ECB_ENGINE_ERROR (0x03),			/**< The ciphertext was not decrypted. */
	AES_ECB_ENGINE_DECRYPT_FAILED = AES_ECB_ENGINE_ERROR (0x04),			/**< The plaintext was not encrypted. */
	AES_ECB_ENGINE_UNSUPPORTED_KEY_LENGTH = AES_ECB_ENGINE_ERROR (0x05),	/**< The encryption key length is not supported by the engine. */
	AES_ECB_ENGINE_INVALID_KEY_LENGTH = AES_ECB_ENGINE_ERROR (0x06),		/**< The key length is not a valid AES-ECB key length. */
	AES_ECB_ENGINE_INVALID_DATA_LENGTH = AES_ECB_ENGINE_ERROR (0x07),		/**< The data length is aligned to the AES block size. */
	AES_ECB_ENGINE_OUT_BUFFER_TOO_SMALL = AES_ECB_ENGINE_ERROR (0x07),		/**< Not enough space in an output buffer provided for the operation. */
	AES_ECB_ENGINE_NO_KEY = AES_ECB_ENGINE_ERROR (0x08),					/**< No key was set prior to encryption/decryption. */
	AES_ECB_ENGINE_HW_NOT_INIT = AES_ECB_ENGINE_ERROR (0x09),				/**< The AES hardware has not been initialized. */
	AES_ECB_ENGINE_SELF_TEST_FAILED = AES_ECB_ENGINE_ERROR (0x0a),			/**< An internal self-test of the AES engine failed. */
	AES_ECB_ENGINE_UNSUPPORTED_OPERATION = AES_ECB_ENGINE_ERROR (0x0b),		/**< The requested operation is not supported. */
	AES_ECB_ENGINE_CLEAR_KEY_FAILED = AES_ECB_ENGINE_ERROR (0x0c),			/**< The encryption key could not be zeroized. */
};


#endif	/* AES_ECB_H_ */
