// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef ASN1_H_
#define ASN1_H_

#include <stdint.h>
#include <stddef.h>
#include "status/rot_status.h"


int asn1_get_der_item_len (const uint8_t *der, size_t der_len);
size_t asn1_get_der_encoded_length (const uint8_t *der, size_t max_length);


#define	ASN1_ENGINE_ERROR(code)			ROT_ERROR (ROT_MODULE_ASN1, code)

/**
 * Error codes that can be generated by a ASN1 handler.
 */
enum {
	ASN1_INVALID_ARGUMENT = ASN1_ENGINE_ERROR (0x00),		/**< Input parameter is null or not valid. */
	ASN1_NO_MEMORY = ASN1_ENGINE_ERROR (0x01),				/**< Memory allocation failed. */
	ASN1_NOT_VALID = ASN1_ENGINE_ERROR (0x02),				/**< ASN1 decoding failed. */
};


#endif /* ASN1_H_ */
