// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef RNG_H_
#define RNG_H_

#include <stdint.h>
#include <stddef.h>
#include "status/rot_status.h"


/**
 * A platform-independent API for generating random numbers.  Random number engine instances are not
 * guaranteed to be thread-safe.
 */
struct rng_engine {
	/**
	 * Generate variable length buffer of random numbers.
	 *
	 * @param engine The RNG engine to use for random number generation.
	 * @param rand_len The number of random bytes to generate.
	 * @param buf The random number buffer to fill. Must be large enough to accommodate rand_len.
	 *
	 * @return 0 if the random buffer was successfully filled or an error code.
	 */
	int (*generate_random_buffer) (struct rng_engine *engine, size_t rand_len, uint8_t *buf);
};


#define	RNG_ENGINE_ERROR(code)		ROT_ERROR (ROT_MODULE_RNG_ENGINE, code)

/**
 * Error codes that can be generated by a hash or HMAC engine.
 */
enum {
	RNG_ENGINE_INVALID_ARGUMENT = RNG_ENGINE_ERROR (0x00),	/**< Input parameter is null or not valid. */
	RNG_ENGINE_NO_MEMORY = RNG_ENGINE_ERROR (0x01),			/**< Memory allocation failed. */
	RNG_ENGINE_RANDOM_FAILED = RNG_ENGINE_ERROR (0x02),		/**< Failed to generate random data. */
	RNG_ENGINE_SELF_TEST_FAILED = RNG_ENGINE_ERROR (0x03),	/**< An internal self-test of the RNG failed. */
};


#endif /* RNG_H_ */
