// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef FATAL_ERROR_HANDLER_H_
#define FATAL_ERROR_HANDLER_H_

#include "logging/debug_log.h"
#include "status/rot_status.h"


/**
 * Defines the interface used to handle fatal errors detected during execution.
 */
struct fatal_error_handler {
	/**
	 * Handle an error that cannot by mitigated by software but does not leave the system in a
	 * generally unusable state.
	 *
	 * @param handler The handler for the fatal error.
	 */
	void (*unrecoverable_error) (const struct fatal_error_handler *handler);

	/**
	 * Handle an error that cannot be mitigated by software and that has left the system in an
	 * unknown state.
	 *
	 * Since the system cannot be relied upon to correctly generate debug log messages, the error
	 * details will need to be handled in some reliable manner that is unlikely to be impacted by
	 * the error condition.
	 *
	 * @param error_code Code identifying the fatal error condition that was encountered.
	 * @param error_log Optional log entry containing additional details about the error condition.
	 * This can be null if there are no additional details to log.
	 */
	void (*panic) (const struct fatal_error_handler *handler, int error_code,
		const struct debug_log_entry_info *error_log);
};


#define	FATAL_ERROR_HANDLER_ERROR(code)		ROT_ERROR (ROT_MODULE_FATAL_ERROR_HANDLER, code)

/**
 * Error codes that can be generated by a fatal error handler.
 */
enum {
	FATAL_ERROR_HANDLER_INVALID_ARGUMENT = FATAL_ERROR_HANDLER_ERROR (0x00),	/**< Input parameter is null or not valid. */
	FATAL_ERROR_HANDLER_NO_MEMORY = FATAL_ERROR_HANDLER_ERROR (0x01),			/**< Memory allocation failed. */
};


#endif	/* FATAL_ERROR_HANDLER_H_ */
