// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef SECURE_DEVICE_UNLOCK_H_
#define SECURE_DEVICE_UNLOCK_H_

#include <stdint.h>
#include <stddef.h>
#include "status/rot_status.h"


/**
 * Handles requests for authenticated device unlock flows.  What functionality is being unlocked
 * depends on the context in which the requests are being executed.
 */
struct secure_device_unlock {
	/**
	 * Get an authorization token that can be used to unlock the device.  This token will generally
	 * be used by an external entity to validate that the operation is allowed to be executed on the
	 * device.
	 *
	 * @param unlock The device unlock handler to query.
	 * @param token Output buffer for the unlock authorization token.
	 * @param length Length of the token buffer.
	 *
	 * @return Length of the generated token or an error code.  Use ROT_IS_ERROR to check the return
	 * value.
	 */
	int (*get_unlock_token) (const struct secure_device_unlock *unlock, uint8_t *token,
		size_t length);

	/**
	 * Apply an authenticated unlock policy to a device.  The contents of the unlock policy will be
	 * determined by the functionality that is being unlocked.  Policy authentication will generally
	 * require signing with a trusted key by an external entity and will typically additionally
	 * require information from the unlock token.
	 *
	 * @param unlock The device unlock handler for the unlock policy.
	 * @param policy The unlock policy that should be authenticated and applied.
	 * @param length Length of the unlock policy.
	 *
	 * @return 0 if the unlock policy was applied successfully or an error code.
	 */
	int (*apply_unlock_policy) (const struct secure_device_unlock *unlock, const uint8_t *policy,
		size_t length);

	/**
	 * Remove any existing unlock policy, whether the policy has taken full effect or not.
	 *
	 * @param unlock The device unlock handler for the unlock policy.
	 *
	 * @param 0 if the unlock policy has been cleared successfully or an error code.
	 */
	int (*clear_unlock_policy) (const struct secure_device_unlock *unlock);
};


#define	SECURE_DEVICE_UNLOCK_ERROR(code)		ROT_ERROR (ROT_MODULE_SECURE_DEVICE_UNLOCK, code)

/**
 * Error codes that can be generated by a handler for unlock requests.
 */
enum {
	SECURE_DEVICE_UNLOCK_INVALID_ARGUMENT = SECURE_DEVICE_UNLOCK_ERROR (0x00),		/**< Input parameter is null or not valid. */
	SECURE_DEVICE_UNLOCK_NO_MEMORY = SECURE_DEVICE_UNLOCK_ERROR (0x01),				/**< Memory allocation failed. */
	SECURE_DEVICE_UNLOCK_GET_TOKEN_FAILED = SECURE_DEVICE_UNLOCK_ERROR (0x02),		/**< Failed to get an unlock token. */
	SECURE_DEVICE_UNLOCK_APPLY_POLICY_FAILED = SECURE_DEVICE_UNLOCK_ERROR (0x03),	/**< Failed to apply an unlock policy. */
	SECURE_DEVICE_UNLOCK_CLEAR_POLICY_FAILED = SECURE_DEVICE_UNLOCK_ERROR (0x04),	/**< Failed to clear an unlock policy. */
	SECURE_DEVICE_UNLOCK_NOT_LOCKED = SECURE_DEVICE_UNLOCK_ERROR (0x05),			/**< Attempt to unlock an unlocked device. */
	SECURE_DEVICE_UNLOCK_COUNTER_EXHAUSTED = SECURE_DEVICE_UNLOCK_ERROR (0x06),		/**< The device unlock counter has reached the max value. */
	SECURE_DEVICE_UNLOCK_UNSUPPORTED = SECURE_DEVICE_UNLOCK_ERROR (0x07),			/**< The requested operation is not supported. */
};


#endif /* SECURE_DEVICE_UNLOCK_H_ */
