// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef RIOT_KEYS_H_
#define RIOT_KEYS_H_

#include <stdint.h>
#include <stddef.h>


/**
 * The structure for storing keys generated by RIoT Core.
 */
struct riot_keys {
	const uint8_t *devid_cert;	/**< The X.509 certificate for the Device ID. */
	size_t devid_cert_length;	/**< The length of the Device ID X.509 certificate. */
	const uint8_t *devid_csr;	/**< The CSR for the Device ID certificate. */
	size_t devid_csr_length;	/**< The length of the Device ID CSR. */
	const uint8_t *alias_key;	/**< The private ECC Alias key. */
	size_t alias_key_length;	/**< The length of the Alias key. */
	const uint8_t *alias_cert;	/**< The X.509 certificate for the Alias key. */
	size_t alias_cert_length;	/**< The length of the Alias X.509 certificate. */
};


#endif /* RIOT_KEYS_H_ */
