// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef PCR_TESTING_H_
#define PCR_TESTING_H_

#include <stdint.h>


extern const uint8_t PCR_TESTING_SHA256_EVENT_TYPE[];
extern const uint8_t PCR_TESTING_SHA256_VERSIONED[];

extern const uint8_t PCR_TESTING_SHA256_FULL_BLOCK_512_HASH_WITH_EVENT[];
extern const uint8_t PCR_TESTING_SHA256_FULL_BLOCK_512_HASH_VERSIONED[];
extern const uint8_t PCR_TESTING_SHA256_FULL_BLOCK_512_HASH_VERSIONED_WITH_EVENT[];

extern const uint8_t PCR_TESTING_SHA256_PCR_MEASUREMENT0[];
extern const uint8_t PCR_TESTING_SHA256_PCR_MEASUREMENT1[];
extern const uint8_t PCR_TESTING_SHA256_PCR_MEASUREMENT2[];

extern const uint8_t PCR_TESTING_SHA256_PCR_NONE_VALID_MEASUREMENT0[];
extern const uint8_t PCR_TESTING_SHA256_PCR_NONE_VALID_MEASUREMENT1[];

extern const uint8_t PCR_TESTING_SHA384_EVENT_TYPE[];
extern const uint8_t PCR_TESTING_SHA384_VERSIONED[];

extern const uint8_t PCR_TESTING_SHA384_FULL_BLOCK_512_HASH_WITH_EVENT[];
extern const uint8_t PCR_TESTING_SHA384_FULL_BLOCK_512_HASH_VERSIONED[];
extern const uint8_t PCR_TESTING_SHA384_FULL_BLOCK_512_HASH_VERSIONED_WITH_EVENT[];

extern const uint8_t PCR_TESTING_SHA384_PCR_MEASUREMENT0[];
extern const uint8_t PCR_TESTING_SHA384_PCR_MEASUREMENT1[];
extern const uint8_t PCR_TESTING_SHA384_PCR_MEASUREMENT2[];

extern const uint8_t PCR_TESTING_SHA384_PCR_NONE_VALID_MEASUREMENT0[];
extern const uint8_t PCR_TESTING_SHA384_PCR_NONE_VALID_MEASUREMENT1[];

extern const uint8_t PCR_TESTING_SHA512_EVENT_TYPE[];
extern const uint8_t PCR_TESTING_SHA512_VERSIONED[];

extern const uint8_t PCR_TESTING_SHA512_FULL_BLOCK_512_HASH_WITH_EVENT[];
extern const uint8_t PCR_TESTING_SHA512_FULL_BLOCK_512_HASH_VERSIONED[];
extern const uint8_t PCR_TESTING_SHA512_FULL_BLOCK_512_HASH_VERSIONED_WITH_EVENT[];

extern const uint8_t PCR_TESTING_SHA512_PCR_MEASUREMENT0[];
extern const uint8_t PCR_TESTING_SHA512_PCR_MEASUREMENT1[];
extern const uint8_t PCR_TESTING_SHA512_PCR_MEASUREMENT2[];

extern const uint8_t PCR_TESTING_SHA512_PCR_NONE_VALID_MEASUREMENT0[];
extern const uint8_t PCR_TESTING_SHA512_PCR_NONE_VALID_MEASUREMENT1[];


#endif /* PCR_TESTING_H_ */
