// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include "platform_api.h"
#include "testing.h"
#include "crypto/hkdf.h"
#include "crypto/hkdf_static.h"
#include "testing/engines/hash_testing_engine.h"
#include "testing/mock/crypto/hash_mock.h"


TEST_SUITE_LABEL ("hkdf");


/**
 * Input keying material for HKDF-Extract testing.  Taken from RFC 5869 test vectors.
 */
const uint8_t HKDF_TESTING_EXTRACT_IKM[] = {
	0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b,
	0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b
};

const size_t HKDF_TESTING_EXTRACT_IKM_LEN = sizeof (HKDF_TESTING_EXTRACT_IKM);

/**
 * Long input keying material for HKDF-Extract testing.  Taken from RFC 5869 test vectors.
 */
const uint8_t HKDF_TESTING_EXTRACT_IKM_LONG[] = {
	0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
	0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f,
	0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f,
	0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f,
	0x40, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0x4e, 0x4f
};

const size_t HKDF_TESTING_EXTRACT_IKM_LONG_LEN = sizeof (HKDF_TESTING_EXTRACT_IKM_LONG);

/**
 * Input keying material for HKDF-Extract testing when no salt is provided.  Taken from RFC 5869
 * test vectors.
 */
const uint8_t HKDF_TESTING_EXTRACT_IKM_NO_SALT[] = {
	0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c,
	0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c
};

const size_t HKDF_TESTING_EXTRACT_IKM_NO_SALT_LEN = sizeof (HKDF_TESTING_EXTRACT_IKM_NO_SALT);

/**
 * Input keying material for HKDF-Extract testing with SHA-1.  Taken from RFC 5869 test vectors.
 */
#define	HKDF_TESTING_EXTRACT_IKM_SHA1			HKDF_TESTING_EXTRACT_IKM

#define	HKDF_TESTING_EXTRACT_IKM_SHA1_LEN		11

/**
 * Salt to use for HKDF-Extract testing.  Taken from RFC 5869 test vectors.
 */
const uint8_t HKDF_TESTING_EXTRACT_SALT[] = {
	0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c
};

const size_t HKDF_TESTING_EXTRACT_SALT_LEN = sizeof (HKDF_TESTING_EXTRACT_SALT);

/**
 * Long salt to use for HKDF-Extract testing.  Taken from RFC 5869 test vectors.
 */
const uint8_t HKDF_TESTING_EXTRACT_SALT_LONG[] = {
	0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d, 0x6e, 0x6f,
	0x70, 0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7a, 0x7b, 0x7c, 0x7d, 0x7e, 0x7f,
	0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f,
	0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0x9b, 0x9c, 0x9d, 0x9e, 0x9f,
	0xa0, 0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7, 0xa8, 0xa9, 0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf
};

const size_t HKDF_TESTING_EXTRACT_SALT_LONG_LEN = sizeof (HKDF_TESTING_EXTRACT_SALT_LONG);

/**
 * Pseudorandom key generated by HKDF-Extract with SHA-256.  Taken from RFC 5869 test vectors.
 */
const uint8_t HKDF_TESTING_EXTRACT_PRK_SHA256[] = {
	0x07, 0x77, 0x09, 0x36, 0x2c, 0x2e, 0x32, 0xdf, 0x0d, 0xdc, 0x3f, 0x0d, 0xc4, 0x7b, 0xba, 0x63,
	0x90, 0xb6, 0xc7, 0x3b, 0xb5, 0x0f, 0x9c, 0x31, 0x22, 0xec, 0x84, 0x4a, 0xd7, 0xc2, 0xb3, 0xe5
};

const size_t HKDF_TESTING_EXTRACT_PRK_SHA256_LEN = sizeof (HKDF_TESTING_EXTRACT_PRK_SHA256);

/**
 * Pseudorandom key generated by HKDF-Extract with SHA-256 using the long IKM and Salt.  Taken from
 * RFC 5869 test vectors.
 */
const uint8_t HKDF_TESTING_EXTRACT_PRK_LONG_SHA256[] = {
	0x06, 0xa6, 0xb8, 0x8c, 0x58, 0x53, 0x36, 0x1a, 0x06, 0x10, 0x4c, 0x9c, 0xeb, 0x35, 0xb4, 0x5c,
	0xef, 0x76, 0x00, 0x14, 0x90, 0x46, 0x71, 0x01, 0x4a, 0x19, 0x3f, 0x40, 0xc1, 0x5f, 0xc2, 0x44
};

const size_t HKDF_TESTING_EXTRACT_PRK_LONG_SHA256_LEN =
	sizeof (HKDF_TESTING_EXTRACT_PRK_LONG_SHA256);

/**
 * Pseudorandom key generated by HKDF-Extract with SHA-256 with zero-length salt.  Taken from
 * RFC 5869 test vectors.
 */
const uint8_t HKDF_TESTING_EXTRACT_PRK_ZERO_SALT_SHA256[] = {
	0x19, 0xef, 0x24, 0xa3, 0x2c, 0x71, 0x7b, 0x16, 0x7f, 0x33, 0xa9, 0x1d, 0x6f, 0x64, 0x8b, 0xdf,
	0x96, 0x59, 0x67, 0x76, 0xaf, 0xdb, 0x63, 0x77, 0xac, 0x43, 0x4c, 0x1c, 0x29, 0x3c, 0xcb, 0x04
};

const size_t HKDF_TESTING_EXTRACT_PRK_ZERO_SALT_SHA256_LEN =
	sizeof (HKDF_TESTING_EXTRACT_PRK_ZERO_SALT_SHA256);

/**
 * Pseudorandom key generated by HKDF-Extract with SHA-256 and no salt provided.
 */
const uint8_t HKDF_TESTING_EXTRACT_PRK_NO_SALT_SHA256[] = {
	0xaa, 0x84, 0x1e, 0x1f, 0x35, 0x74, 0xf3, 0x2d, 0x13, 0xfb, 0xa8, 0x00, 0x5f, 0xcd, 0x9b, 0x8d,
	0x77, 0x67, 0x82, 0xa5, 0xdf, 0xa1, 0x92, 0x38, 0x92, 0xfd, 0x8b, 0x63, 0x5d, 0x3a, 0x89, 0xdf
};

const size_t HKDF_TESTING_EXTRACT_PRK_NO_SALT_SHA256_LEN =
	sizeof (HKDF_TESTING_EXTRACT_PRK_NO_SALT_SHA256);

/**
 * Pseudorandom key generated by HKDF-Extract with SHA-1.  Taken from RFC 5869 test vectors.
 */
const uint8_t HKDF_TESTING_EXTRACT_PRK_SHA1[] = {
	0x9b, 0x6c, 0x18, 0xc4, 0x32, 0xa7, 0xbf, 0x8f, 0x0e, 0x71, 0xc8, 0xeb, 0x88, 0xf4, 0xb3, 0x0b,
	0xaa, 0x2b, 0xa2, 0x43
};

const size_t HKDF_TESTING_EXTRACT_PRK_SHA1_LEN = sizeof (HKDF_TESTING_EXTRACT_PRK_SHA1);

/**
 * Pseudorandom key generated by HKDF-Extract with SHA-1 using the long IKM and Salt.  Taken from
 * RFC 5869 test vectors.
 */
const uint8_t HKDF_TESTING_EXTRACT_PRK_LONG_SHA1[] = {
	0x8a, 0xda, 0xe0, 0x9a, 0x2a, 0x30, 0x70, 0x59, 0x47, 0x8d, 0x30, 0x9b, 0x26, 0xc4, 0x11, 0x5a,
	0x22, 0x4c, 0xfa, 0xf6
};

const size_t HKDF_TESTING_EXTRACT_PRK_LONG_SHA1_LEN = sizeof (HKDF_TESTING_EXTRACT_PRK_LONG_SHA1);

/**
 * Pseudorandom key generated by HKDF-Extract with SHA-1 with zero-length salt.  Taken from RFC 5869
 * test vectors.
 */
const uint8_t HKDF_TESTING_EXTRACT_PRK_ZERO_SALT_SHA1[] = {
	0xda, 0x8c, 0x8a, 0x73, 0xc7, 0xfa, 0x77, 0x28, 0x8e, 0xc6, 0xf5, 0xe7, 0xc2, 0x97, 0x78, 0x6a,
	0xa0, 0xd3, 0x2d, 0x01
};

const size_t HKDF_TESTING_EXTRACT_PRK_ZERO_SALT_SHA1_LEN =
	sizeof (HKDF_TESTING_EXTRACT_PRK_ZERO_SALT_SHA1);

/**
 * Pseudorandom key generated by HKDF-Extract with SHA-1 and no salt provided.  Taken from RFC 5869
 * test vectors.
 */
const uint8_t HKDF_TESTING_EXTRACT_PRK_NO_SALT_SHA1[] = {
	0x2a, 0xdc, 0xca, 0xda, 0x18, 0x77, 0x9e, 0x7c, 0x20, 0x77, 0xad, 0x2e, 0xb1, 0x9d, 0x3f, 0x3e,
	0x73, 0x13, 0x85, 0xdd
};

const size_t HKDF_TESTING_EXTRACT_PRK_NO_SALT_SHA1_LEN =
	sizeof (HKDF_TESTING_EXTRACT_PRK_NO_SALT_SHA1);

/**
 * KDF context for HKDF-Expand testing.  Taken from RFC 5869 test vectors.
 */
const uint8_t HKDF_TESTING_EXPAND_INFO[] = {
	0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9
};

const size_t HKDF_TESTING_EXPAND_INFO_LEN = sizeof (HKDF_TESTING_EXPAND_INFO);

/**
 * Long KDF context for HKDF-Expand testing.  Taken from RFC 5869 test vectors.
 */
const uint8_t HKDF_TESTING_EXPAND_INFO_LONG[] = {
	0xb0, 0xb1, 0xb2, 0xb3, 0xb4, 0xb5, 0xb6, 0xb7, 0xb8, 0xb9, 0xba, 0xbb, 0xbc, 0xbd, 0xbe, 0xbf,
	0xc0, 0xc1, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9, 0xca, 0xcb, 0xcc, 0xcd, 0xce, 0xcf,
	0xd0, 0xd1, 0xd2, 0xd3, 0xd4, 0xd5, 0xd6, 0xd7, 0xd8, 0xd9, 0xda, 0xdb, 0xdc, 0xdd, 0xde, 0xdf,
	0xe0, 0xe1, 0xe2, 0xe3, 0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xeb, 0xec, 0xed, 0xee, 0xef,
	0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe, 0xff
};

const size_t HKDF_TESTING_EXPAND_INFO_LONG_LEN = sizeof (HKDF_TESTING_EXPAND_INFO_LONG);

/**
 * Output key material generated by HKDF-Expand with SHA-256.  Taken from RFC 5869 test vectors.
 *
 * Uses HKDF_TESTING_EXTRACT_PRK_SHA256.
 */
const uint8_t HKDF_TESTING_EXPAND_OKM_SHA256[] = {
	0x3c, 0xb2, 0x5f, 0x25, 0xfa, 0xac, 0xd5, 0x7a, 0x90, 0x43, 0x4f, 0x64, 0xd0, 0x36, 0x2f, 0x2a,
	0x2d, 0x2d, 0x0a, 0x90, 0xcf, 0x1a, 0x5a, 0x4c, 0x5d, 0xb0, 0x2d, 0x56, 0xec, 0xc4, 0xc5, 0xbf,
	0x34, 0x00, 0x72, 0x08, 0xd5, 0xb8, 0x87, 0x18, 0x58, 0x65
};

const size_t HKDF_TESTING_EXPAND_OKM_SHA256_LEN = sizeof (HKDF_TESTING_EXPAND_OKM_SHA256);

/**
 * Long output key material generated by HKDF-Expand with SHA-256.  Taken from RFC 5869 test
 * vectors.
 *
 * Uses HKDF_TESTING_EXTRACT_PRK_LONG_SHA256.
 */
const uint8_t HKDF_TESTING_EXPAND_OKM_LONG_SHA256[] = {
	0xb1, 0x1e, 0x39, 0x8d, 0xc8, 0x03, 0x27, 0xa1, 0xc8, 0xe7, 0xf7, 0x8c, 0x59, 0x6a, 0x49, 0x34,
	0x4f, 0x01, 0x2e, 0xda, 0x2d, 0x4e, 0xfa, 0xd8, 0xa0, 0x50, 0xcc, 0x4c, 0x19, 0xaf, 0xa9, 0x7c,
	0x59, 0x04, 0x5a, 0x99, 0xca, 0xc7, 0x82, 0x72, 0x71, 0xcb, 0x41, 0xc6, 0x5e, 0x59, 0x0e, 0x09,
	0xda, 0x32, 0x75, 0x60, 0x0c, 0x2f, 0x09, 0xb8, 0x36, 0x77, 0x93, 0xa9, 0xac, 0xa3, 0xdb, 0x71,
	0xcc, 0x30, 0xc5, 0x81, 0x79, 0xec, 0x3e, 0x87, 0xc1, 0x4c, 0x01, 0xd5, 0xc1, 0xf3, 0x43, 0x4f,
	0x1d, 0x87
};

const size_t HKDF_TESTING_EXPAND_OKM_LONG_SHA256_LEN =
	sizeof (HKDF_TESTING_EXPAND_OKM_LONG_SHA256);

/**
 * Output key material generated by HKDF-Expand with SHA-256 with no additional KDF context.  Taken
 * from RFC 5869 test vectors.
 *
 * Uses HKDF_TESTING_EXTRACT_PRK_ZERO_SALT_SHA256.
 */
const uint8_t HKDF_TESTING_EXPAND_OKM_NO_INFO_SHA256[] = {
	0x8d, 0xa4, 0xe7, 0x75, 0xa5, 0x63, 0xc1, 0x8f, 0x71, 0x5f, 0x80, 0x2a, 0x06, 0x3c, 0x5a, 0x31,
	0xb8, 0xa1, 0x1f, 0x5c, 0x5e, 0xe1, 0x87, 0x9e, 0xc3, 0x45, 0x4e, 0x5f, 0x3c, 0x73, 0x8d, 0x2d,
	0x9d, 0x20, 0x13, 0x95, 0xfa, 0xa4, 0xb6, 0x1a, 0x96, 0xc8
};

const size_t HKDF_TESTING_EXPAND_OKM_NO_INFO_SHA256_LEN =
	sizeof (HKDF_TESTING_EXPAND_OKM_NO_INFO_SHA256);

/**
 * Output key material generated by HKDF-Expand with SHA-1.  Taken from RFC 5869 test vectors.
 *
 * Uses HKDF_TESTING_EXTRACT_PRK_SHA1.
 */
const uint8_t HKDF_TESTING_EXPAND_OKM_SHA1[] = {
	0x08, 0x5a, 0x01, 0xea, 0x1b, 0x10, 0xf3, 0x69, 0x33, 0x06, 0x8b, 0x56, 0xef, 0xa5, 0xad, 0x81,
	0xa4, 0xf1, 0x4b, 0x82, 0x2f, 0x5b, 0x09, 0x15, 0x68, 0xa9, 0xcd, 0xd4, 0xf1, 0x55, 0xfd, 0xa2,
	0xc2, 0x2e, 0x42, 0x24, 0x78, 0xd3, 0x05, 0xf3, 0xf8, 0x96
};

const size_t HKDF_TESTING_EXPAND_OKM_SHA1_LEN = sizeof (HKDF_TESTING_EXPAND_OKM_SHA1);

/**
 * Long output key material generated by HKDF-Expand with SHA-1.  Taken from RFC 5869 test
 * vectors.
 *
 * Uses HKDF_TESTING_EXTRACT_PRK_LONG_SHA1.
 */
const uint8_t HKDF_TESTING_EXPAND_OKM_LONG_SHA1[] = {
	0x0b, 0xd7, 0x70, 0xa7, 0x4d, 0x11, 0x60, 0xf7, 0xc9, 0xf1, 0x2c, 0xd5, 0x91, 0x2a, 0x06, 0xeb,
	0xff, 0x6a, 0xdc, 0xae, 0x89, 0x9d, 0x92, 0x19, 0x1f, 0xe4, 0x30, 0x56, 0x73, 0xba, 0x2f, 0xfe,
	0x8f, 0xa3, 0xf1, 0xa4, 0xe5, 0xad, 0x79, 0xf3, 0xf3, 0x34, 0xb3, 0xb2, 0x02, 0xb2, 0x17, 0x3c,
	0x48, 0x6e, 0xa3, 0x7c, 0xe3, 0xd3, 0x97, 0xed, 0x03, 0x4c, 0x7f, 0x9d, 0xfe, 0xb1, 0x5c, 0x5e,
	0x92, 0x73, 0x36, 0xd0, 0x44, 0x1f, 0x4c, 0x43, 0x00, 0xe2, 0xcf, 0xf0, 0xd0, 0x90, 0x0b, 0x52,
	0xd3, 0xb4
};

const size_t HKDF_TESTING_EXPAND_OKM_LONG_SHA1_LEN =
	sizeof (HKDF_TESTING_EXPAND_OKM_LONG_SHA1);

/**
 * Output key material generated by HKDF-Expand with SHA-1 with no additional KDF context.  Taken
 * from RFC 5869 test vectors.
 *
 * Uses HKDF_TESTING_EXTRACT_PRK_ZERO_SALT_SHA1.
 */
const uint8_t HKDF_TESTING_EXPAND_OKM_NO_INFO_SHA1[] = {
	0x0a, 0xc1, 0xaf, 0x70, 0x02, 0xb3, 0xd7, 0x61, 0xd1, 0xe5, 0x52, 0x98, 0xda, 0x9d, 0x05, 0x06,
	0xb9, 0xae, 0x52, 0x05, 0x72, 0x20, 0xa3, 0x06, 0xe0, 0x7b, 0x6b, 0x87, 0xe8, 0xdf, 0x21, 0xd0,
	0xea, 0x00, 0x03, 0x3d, 0xe0, 0x39, 0x84, 0xd3, 0x49, 0x18
};

const size_t HKDF_TESTING_EXPAND_OKM_NO_INFO_SHA1_LEN =
	sizeof (HKDF_TESTING_EXPAND_OKM_NO_INFO_SHA1);

/**
 * Output key material generated by HKDF-Expand with SHA-1 with no additional KDF context.  Taken
 * from RFC 5869 test vectors.
 *
 * Uses HKDF_TESTING_EXTRACT_PRK_NO_SALT_SHA1.
 */
const uint8_t HKDF_TESTING_EXPAND_OKM_NO_SALT_SHA1[] = {
	0x2c, 0x91, 0x11, 0x72, 0x04, 0xd7, 0x45, 0xf3, 0x50, 0x0d, 0x63, 0x6a, 0x62, 0xf6, 0x4f, 0x0a,
	0xb3, 0xba, 0xe5, 0x48, 0xaa, 0x53, 0xd4, 0x23, 0xb0, 0xd1, 0xf2, 0x7e, 0xbb, 0xa6, 0xf5, 0xe5,
	0x67, 0x3a, 0x08, 0x1d, 0x70, 0xcc, 0xe7, 0xac, 0xfc, 0x48
};

const size_t HKDF_TESTING_EXPAND_OKM_NO_SALT_SHA1_LEN =
	sizeof (HKDF_TESTING_EXPAND_OKM_NO_SALT_SHA1);


/**
 * Test dependencies for HKDF.
 */
struct hkdf_testing {
	HASH_TESTING_ENGINE (hash);			/**< Hash engine for test. */
	struct hash_engine_mock hash_mock;	/**< Mock for the hash engine. */
	struct hkdf_state state;			/**< Variable context for HKDF. */
	struct hkdf test;					/**< HKDF under test. */
};


/**
 * Helper to initialize all dependencies for testing.
 *
 * @param test The test framework.
 * @param hkdf Testing dependencies to initialize.
 */
static void hkdf_testing_init_dependencies (CuTest *test, struct hkdf_testing *hkdf)
{
	int status;

	status = HASH_TESTING_ENGINE_INIT (&hkdf->hash);
	CuAssertIntEquals (test, 0, status);

	status = hash_mock_init (&hkdf->hash_mock);
	CuAssertIntEquals (test, 0, status);
}

/**
 * Helper to release all testing dependencies.
 *
 * @param test The test framework.
 * @param hkdf Testing dependencies to release.
 */
static void hkdf_testing_release_dependencies (CuTest *test, struct hkdf_testing *hkdf)
{
	int status;

	status = hash_mock_validate_and_release (&hkdf->hash_mock);
	CuAssertIntEquals (test, 0, status);

	HASH_TESTING_ENGINE_RELEASE (&hkdf->hash);
}

/**
 * Initialize HKDF for testing.
 *
 * @param test The test framework.
 * @param hkdf Testing components to initialize.
 */
static void hkdf_testing_init (CuTest *test, struct hkdf_testing *hkdf)
{
	int status;

	hkdf_testing_init_dependencies (test, hkdf);

	status = hkdf_init (&hkdf->test, &hkdf->state, &hkdf->hash.base);
	CuAssertIntEquals (test, 0, status);
}

/**
 * Initialize a static HKDF for testing.
 *
 * @param test The test framework.
 * @param hkdf Testing components to initialize.
 */
static void hkdf_testing_init_static (CuTest *test, struct hkdf_testing *hkdf)
{
	int status;

	hkdf_testing_init_dependencies (test, hkdf);

	status = hkdf_init_state (&hkdf->test);
	CuAssertIntEquals (test, 0, status);
}

/**
 * Initialize HKDF for testing using a mock for hash operations.
 *
 * @param test The test framework.
 * @param hkdf Testing components to initialize.
 */
static void hkdf_testing_init_with_mock (CuTest *test, struct hkdf_testing *hkdf)
{
	int status;

	hkdf_testing_init_dependencies (test, hkdf);

	status = hkdf_init (&hkdf->test, &hkdf->state, &hkdf->hash_mock.base);
	CuAssertIntEquals (test, 0, status);
}

/**
 * Release test components and validate all mocks.
 *
 * @param test The test framework.
 * @param hkdf Testing components to release.
 */
static void hkdf_testing_release (CuTest *test, struct hkdf_testing *hkdf)
{
	hkdf_testing_release_dependencies (test, hkdf);

	hkdf_release (&hkdf->test);
}


/*******************
 * Test cases
 *******************/

static void hkdf_test_init (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;

	TEST_START;

	hkdf_testing_init_dependencies (test, &hkdf);

	status = hkdf_init (&hkdf.test, &hkdf.state, &hkdf.hash.base);
	CuAssertIntEquals (test, 0, status);

	CuAssertPtrNotNull (test, hkdf.test.base.extract);
	CuAssertPtrNotNull (test, hkdf.test.base.expand);
	CuAssertPtrNotNull (test, hkdf.test.base.clear_prk);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_init_null (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;

	TEST_START;

	hkdf_testing_init_dependencies (test, &hkdf);

	status = hkdf_init (NULL, &hkdf.state, &hkdf.hash.base);
	CuAssertIntEquals (test, HKDF_INVALID_ARGUMENT, status);

	status = hkdf_init (&hkdf.test, NULL, &hkdf.hash.base);
	CuAssertIntEquals (test, HKDF_INVALID_ARGUMENT, status);

	status = hkdf_init (&hkdf.test, &hkdf.state, NULL);
	CuAssertIntEquals (test, HKDF_INVALID_ARGUMENT, status);

	hkdf_testing_release_dependencies (test, &hkdf);
}

static void hkdf_test_static_init (CuTest *test)
{
	struct hkdf_testing hkdf = {
		.test = hkdf_static_init (&hkdf.state, &hkdf.hash.base)
	};
	int status;

	TEST_START;

	CuAssertPtrNotNull (test, hkdf.test.base.extract);
	CuAssertPtrNotNull (test, hkdf.test.base.expand);
	CuAssertPtrNotNull (test, hkdf.test.base.clear_prk);

	hkdf_testing_init_dependencies (test, &hkdf);

	status = hkdf_init_state (&hkdf.test);
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_static_init_null (CuTest *test)
{
	struct hkdf_testing hkdf;
	struct hkdf null_state = hkdf_static_init (NULL, &hkdf.hash.base);
	struct hkdf null_hash = hkdf_static_init (&hkdf.state, NULL);
	int status;

	TEST_START;

	hkdf_testing_init_dependencies (test, &hkdf);

	status = hkdf_init_state (NULL);
	CuAssertIntEquals (test, HKDF_INVALID_ARGUMENT, status);

	status = hkdf_init_state (&null_state);
	CuAssertIntEquals (test, HKDF_INVALID_ARGUMENT, status);

	status = hkdf_init_state (&null_hash);
	CuAssertIntEquals (test, HKDF_INVALID_ARGUMENT, status);

	hkdf_testing_release_dependencies (test, &hkdf);
}

static void hkdf_test_release_null (CuTest *test)
{
	TEST_START;

	hkdf_release (NULL);
}

static void hkdf_test_extract_sha256 (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	/* The only way to test this in isolation and know that the PRK is generated correctly is to
	 * look at the internal state. */
	status = testing_validate_array (HKDF_TESTING_EXTRACT_PRK_SHA256, hkdf.state.prk,
		HKDF_TESTING_EXTRACT_PRK_SHA256_LEN);
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_extract_sha256_long_ikm (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256,
		HKDF_TESTING_EXTRACT_IKM_LONG, HKDF_TESTING_EXTRACT_IKM_LONG_LEN,
		HKDF_TESTING_EXTRACT_SALT_LONG, HKDF_TESTING_EXTRACT_SALT_LONG_LEN);
	CuAssertIntEquals (test, 0, status);

	/* The only way to test this in isolation and know that the PRK is generated correctly is to
	 * look at the internal state. */
	status = testing_validate_array (HKDF_TESTING_EXTRACT_PRK_LONG_SHA256, hkdf.state.prk,
		HKDF_TESTING_EXTRACT_PRK_LONG_SHA256_LEN);
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_extract_sha256_zero_length_salt (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, 0);
	CuAssertIntEquals (test, 0, status);

	/* The only way to test this in isolation and know that the PRK is generated correctly is to
	 * look at the internal state. */
	status = testing_validate_array (HKDF_TESTING_EXTRACT_PRK_ZERO_SALT_SHA256, hkdf.state.prk,
		HKDF_TESTING_EXTRACT_PRK_ZERO_SALT_SHA256_LEN);
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_extract_sha256_no_salt_provided (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256,
		HKDF_TESTING_EXTRACT_IKM_NO_SALT, HKDF_TESTING_EXTRACT_IKM_NO_SALT_LEN, NULL, 0);
	CuAssertIntEquals (test, 0, status);

	/* The only way to test this in isolation and know that the PRK is generated correctly is to
	 * look at the internal state. */
	status = testing_validate_array (HKDF_TESTING_EXTRACT_PRK_NO_SALT_SHA256, hkdf.state.prk,
		HKDF_TESTING_EXTRACT_PRK_NO_SALT_SHA256_LEN);
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

#ifdef HASH_ENABLE_SHA1
static void hkdf_test_extract_sha1 (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA1, HKDF_TESTING_EXTRACT_IKM_SHA1,
		HKDF_TESTING_EXTRACT_IKM_SHA1_LEN, HKDF_TESTING_EXTRACT_SALT,
		HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	/* The only way to test this in isolation and know that the PRK is generated correctly is to
	 * look at the internal state. */
	status = testing_validate_array (HKDF_TESTING_EXTRACT_PRK_SHA1, hkdf.state.prk,
		HKDF_TESTING_EXTRACT_PRK_SHA1_LEN);
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_extract_sha1_long_ikm (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA1, HKDF_TESTING_EXTRACT_IKM_LONG,
		HKDF_TESTING_EXTRACT_IKM_LONG_LEN, HKDF_TESTING_EXTRACT_SALT_LONG,
		HKDF_TESTING_EXTRACT_SALT_LONG_LEN);
	CuAssertIntEquals (test, 0, status);

	/* The only way to test this in isolation and know that the PRK is generated correctly is to
	 * look at the internal state. */
	status = testing_validate_array (HKDF_TESTING_EXTRACT_PRK_LONG_SHA1, hkdf.state.prk,
		HKDF_TESTING_EXTRACT_PRK_LONG_SHA1_LEN);
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_extract_sha1_zero_length_salt (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA1, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, 0);
	CuAssertIntEquals (test, 0, status);

	/* The only way to test this in isolation and know that the PRK is generated correctly is to
	 * look at the internal state. */
	status = testing_validate_array (HKDF_TESTING_EXTRACT_PRK_ZERO_SALT_SHA1, hkdf.state.prk,
		HKDF_TESTING_EXTRACT_PRK_ZERO_SALT_SHA1_LEN);
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_extract_sha1_no_salt_provided (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA1,
		HKDF_TESTING_EXTRACT_IKM_NO_SALT, HKDF_TESTING_EXTRACT_IKM_NO_SALT_LEN, NULL, 0);
	CuAssertIntEquals (test, 0, status);

	/* The only way to test this in isolation and know that the PRK is generated correctly is to
	 * look at the internal state. */
	status = testing_validate_array (HKDF_TESTING_EXTRACT_PRK_NO_SALT_SHA1, hkdf.state.prk,
		HKDF_TESTING_EXTRACT_PRK_NO_SALT_SHA1_LEN);
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}
#endif

static void hkdf_test_extract_multiple_calls (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t zero[HASH_MAX_HASH_LEN] = {0};

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256,
		HKDF_TESTING_EXTRACT_IKM_LONG, HKDF_TESTING_EXTRACT_IKM_LONG_LEN,
		HKDF_TESTING_EXTRACT_SALT_LONG, HKDF_TESTING_EXTRACT_SALT_LONG_LEN);
	CuAssertIntEquals (test, 0, status);

	/* The only way to test this in isolation and know that the PRK is generated correctly is to
	 * look at the internal state. */
	status = testing_validate_array (HKDF_TESTING_EXTRACT_PRK_LONG_SHA256, hkdf.state.prk,
		HKDF_TESTING_EXTRACT_PRK_LONG_SHA256_LEN);
	CuAssertIntEquals (test, 0, status);

	status = testing_validate_array (zero, &hkdf.state.prk[HKDF_TESTING_EXTRACT_PRK_SHA256_LEN],
		sizeof (hkdf.state.prk) - HKDF_TESTING_EXTRACT_PRK_SHA256_LEN);
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

#ifdef HASH_ENABLE_SHA1
static void hkdf_test_extract_multiple_calls_different_hash_algorithms (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t zero[HASH_MAX_HASH_LEN] = {0};

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA1, HKDF_TESTING_EXTRACT_IKM_SHA1,
		HKDF_TESTING_EXTRACT_IKM_SHA1_LEN, HKDF_TESTING_EXTRACT_SALT,
		HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	/* The only way to test this in isolation and know that the PRK is generated correctly is to
	 * look at the internal state. */
	status = testing_validate_array (HKDF_TESTING_EXTRACT_PRK_SHA1, hkdf.state.prk,
		HKDF_TESTING_EXTRACT_PRK_SHA1_LEN);
	CuAssertIntEquals (test, 0, status);

	status = testing_validate_array (zero, &hkdf.state.prk[HKDF_TESTING_EXTRACT_PRK_SHA1_LEN],
		sizeof (hkdf.state.prk) - HKDF_TESTING_EXTRACT_PRK_SHA1_LEN);
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}
#endif

static void hkdf_test_extract_static_init (CuTest *test)
{
	struct hkdf_testing hkdf = {
		.test = hkdf_static_init (&hkdf.state, &hkdf.hash.base)
	};
	int status;

	TEST_START;

	hkdf_testing_init_static (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	/* The only way to test this in isolation and know that the PRK is generated correctly is to
	 * look at the internal state. */
	status = testing_validate_array (HKDF_TESTING_EXTRACT_PRK_SHA256, hkdf.state.prk,
		HKDF_TESTING_EXTRACT_PRK_SHA256_LEN);
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_extract_null (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (NULL, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, HKDF_INVALID_ARGUMENT, status);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, NULL,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, HKDF_INVALID_ARGUMENT, status);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM, 0,
		HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, HKDF_INVALID_ARGUMENT, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_extract_unknown_hash_algorithm (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_INVALID, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, HASH_ENGINE_UNKNOWN_HASH, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_extract_hmac_error (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;

	TEST_START;

	hkdf_testing_init_with_mock (test, &hkdf);

	status = mock_expect (&hkdf.hash_mock.mock, hkdf.hash_mock.base.start_sha256, &hkdf.hash_mock,
		HASH_ENGINE_START_SHA256_FAILED);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, HASH_ENGINE_START_SHA256_FAILED, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_sha256_hash_length_key (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[SHA256_HASH_LENGTH];

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO,
		HKDF_TESTING_EXPAND_INFO_LEN, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	status = testing_validate_array (HKDF_TESTING_EXPAND_OKM_SHA256, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_sha256_less_than_hash_length_key (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[SHA256_HASH_LENGTH] = {0};
	uint8_t zero[SHA256_HASH_LENGTH] = {0};
	size_t key_length = SHA256_HASH_LENGTH / 2;

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO,
		HKDF_TESTING_EXPAND_INFO_LEN, key, key_length);
	CuAssertIntEquals (test, 0, status);

	status = testing_validate_array (HKDF_TESTING_EXPAND_OKM_SHA256, key, key_length);
	CuAssertIntEquals (test, 0, status);

	status = testing_validate_array (zero, &key[key_length], sizeof (key) - key_length);
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_sha256_more_than_hash_length_key (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[HKDF_TESTING_EXPAND_OKM_SHA256_LEN];

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO,
		HKDF_TESTING_EXPAND_INFO_LEN, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	status = testing_validate_array (HKDF_TESTING_EXPAND_OKM_SHA256, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_sha256_long_ikm (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[HKDF_TESTING_EXPAND_OKM_LONG_SHA256_LEN];

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256,
		HKDF_TESTING_EXTRACT_IKM_LONG, HKDF_TESTING_EXTRACT_IKM_LONG_LEN,
		HKDF_TESTING_EXTRACT_SALT_LONG, HKDF_TESTING_EXTRACT_SALT_LONG_LEN);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO_LONG,
		HKDF_TESTING_EXPAND_INFO_LONG_LEN, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	status = testing_validate_array (HKDF_TESTING_EXPAND_OKM_LONG_SHA256, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_sha256_no_info (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[HKDF_TESTING_EXPAND_OKM_NO_INFO_SHA256_LEN];

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, NULL, 0);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.expand (&hkdf.test.base, NULL, 0, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	status = testing_validate_array (HKDF_TESTING_EXPAND_OKM_NO_INFO_SHA256, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

#ifdef HASH_ENABLE_SHA1
static void hkdf_test_expand_sha1_hash_length_key (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[SHA1_HASH_LENGTH];

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA1, HKDF_TESTING_EXTRACT_IKM_SHA1,
		HKDF_TESTING_EXTRACT_IKM_SHA1_LEN, HKDF_TESTING_EXTRACT_SALT,
		HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO,
		HKDF_TESTING_EXPAND_INFO_LEN, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	status = testing_validate_array (HKDF_TESTING_EXPAND_OKM_SHA1, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_sha1_less_than_hash_length_key (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[SHA1_HASH_LENGTH] = {0};
	uint8_t zero[SHA1_HASH_LENGTH] = {0};
	size_t key_length = SHA1_HASH_LENGTH / 2;

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA1, HKDF_TESTING_EXTRACT_IKM_SHA1,
		HKDF_TESTING_EXTRACT_IKM_SHA1_LEN, HKDF_TESTING_EXTRACT_SALT,
		HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO,
		HKDF_TESTING_EXPAND_INFO_LEN, key, key_length);
	CuAssertIntEquals (test, 0, status);

	status = testing_validate_array (HKDF_TESTING_EXPAND_OKM_SHA1, key, key_length);
	CuAssertIntEquals (test, 0, status);

	status = testing_validate_array (zero, &key[key_length], sizeof (key) - key_length);
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_sha1_more_than_hash_length_key (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[HKDF_TESTING_EXPAND_OKM_SHA1_LEN];

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA1, HKDF_TESTING_EXTRACT_IKM_SHA1,
		HKDF_TESTING_EXTRACT_IKM_SHA1_LEN, HKDF_TESTING_EXTRACT_SALT,
		HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO,
		HKDF_TESTING_EXPAND_INFO_LEN, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	status = testing_validate_array (HKDF_TESTING_EXPAND_OKM_SHA1, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_sha1_long_ikm (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[HKDF_TESTING_EXPAND_OKM_LONG_SHA1_LEN];

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA1, HKDF_TESTING_EXTRACT_IKM_LONG,
		HKDF_TESTING_EXTRACT_IKM_LONG_LEN, HKDF_TESTING_EXTRACT_SALT_LONG,
		HKDF_TESTING_EXTRACT_SALT_LONG_LEN);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO_LONG,
		HKDF_TESTING_EXPAND_INFO_LONG_LEN, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	status = testing_validate_array (HKDF_TESTING_EXPAND_OKM_LONG_SHA1, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_sha1_no_info (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[HKDF_TESTING_EXPAND_OKM_NO_INFO_SHA1_LEN];

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA1, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, 0);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.expand (&hkdf.test.base, NULL, 0, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	status = testing_validate_array (HKDF_TESTING_EXPAND_OKM_NO_INFO_SHA1, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_sha1_no_salt_provided (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[HKDF_TESTING_EXPAND_OKM_NO_SALT_SHA1_LEN];

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA1,
		HKDF_TESTING_EXTRACT_IKM_NO_SALT, HKDF_TESTING_EXTRACT_IKM_NO_SALT_LEN, NULL, 0);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.expand (&hkdf.test.base, NULL, 0, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	status = testing_validate_array (HKDF_TESTING_EXPAND_OKM_NO_SALT_SHA1, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}
#endif

static void hkdf_test_expand_static_init (CuTest *test)
{
	struct hkdf_testing hkdf = {
		.test = hkdf_static_init (&hkdf.state, &hkdf.hash.base)
	};
	int status;
	uint8_t key[HKDF_TESTING_EXPAND_OKM_SHA256_LEN];

	TEST_START;

	hkdf_testing_init_static (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO,
		HKDF_TESTING_EXPAND_INFO_LEN, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	status = testing_validate_array (HKDF_TESTING_EXPAND_OKM_SHA256, key, sizeof (key));
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_null (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[SHA256_HASH_LENGTH];

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.expand (NULL, HKDF_TESTING_EXPAND_INFO, HKDF_TESTING_EXPAND_INFO_LEN,
		key, sizeof (key));
	CuAssertIntEquals (test, HKDF_INVALID_ARGUMENT, status);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO,
		HKDF_TESTING_EXPAND_INFO_LEN, NULL, sizeof (key));
	CuAssertIntEquals (test, HKDF_INVALID_ARGUMENT, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_no_extract (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[SHA256_HASH_LENGTH];

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO,
		HKDF_TESTING_EXPAND_INFO_LEN, key, sizeof (key));
	CuAssertIntEquals (test, HKDF_NO_PRK_AVAILABLE, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_no_extract_static_init (CuTest *test)
{
	struct hkdf_testing hkdf = {
		.test = hkdf_static_init (&hkdf.state, &hkdf.hash.base)
	};
	int status;
	uint8_t key[SHA256_HASH_LENGTH];

	TEST_START;

	hkdf_testing_init_static (test, &hkdf);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO,
		HKDF_TESTING_EXPAND_INFO_LEN, key, sizeof (key));
	CuAssertIntEquals (test, HKDF_NO_PRK_AVAILABLE, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_unknown_hash (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[SHA256_HASH_LENGTH];

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_INVALID, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, HASH_ENGINE_UNKNOWN_HASH, status);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO,
		HKDF_TESTING_EXPAND_INFO_LEN, key, sizeof (key));
	CuAssertIntEquals (test, HKDF_NO_PRK_AVAILABLE, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_after_extract_failure (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[SHA256_HASH_LENGTH];

	TEST_START;

	hkdf_testing_init_with_mock (test, &hkdf);

	status = mock_expect (&hkdf.hash_mock.mock, hkdf.hash_mock.base.start_sha256, &hkdf.hash_mock,
		HASH_ENGINE_START_SHA256_FAILED);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, HASH_ENGINE_START_SHA256_FAILED, status);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO,
		HKDF_TESTING_EXPAND_INFO_LEN, key, sizeof (key));
	CuAssertIntEquals (test, HKDF_NO_PRK_AVAILABLE, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_after_extract_failure_after_extract_success (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[SHA256_HASH_LENGTH];

	TEST_START;

	hkdf_testing_init_with_mock (test, &hkdf);

	/* Successful extract call. */
	status = hash_mock_expect_hmac (&hkdf.hash_mock, HKDF_TESTING_EXTRACT_SALT,
		HKDF_TESTING_EXTRACT_SALT_LEN, HKDF_TESTING_EXTRACT_IKM, HKDF_TESTING_EXTRACT_IKM_LEN, NULL,
		SHA256_HASH_LENGTH, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_PRK_SHA256,
		HKDF_TESTING_EXTRACT_PRK_SHA256_LEN);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	/* Failed extract call. */
	status = mock_expect (&hkdf.hash_mock.mock, hkdf.hash_mock.base.start_sha256, &hkdf.hash_mock,
		HASH_ENGINE_START_SHA256_FAILED);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, HASH_ENGINE_START_SHA256_FAILED, status);

	/* Attempt to expand. */
	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO,
		HKDF_TESTING_EXPAND_INFO_LEN, key, sizeof (key));
	CuAssertIntEquals (test, HKDF_NO_PRK_AVAILABLE, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_expand_hmac_error (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[SHA256_HASH_LENGTH];

	TEST_START;

	hkdf_testing_init_with_mock (test, &hkdf);

	/* Successful extract call. */
	status = hash_mock_expect_hmac (&hkdf.hash_mock, HKDF_TESTING_EXTRACT_SALT,
		HKDF_TESTING_EXTRACT_SALT_LEN, HKDF_TESTING_EXTRACT_IKM, HKDF_TESTING_EXTRACT_IKM_LEN, NULL,
		SHA256_HASH_LENGTH, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_PRK_SHA256,
		HKDF_TESTING_EXTRACT_PRK_SHA256_LEN);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	status = mock_expect (&hkdf.hash_mock.mock, hkdf.hash_mock.base.start_sha256, &hkdf.hash_mock,
		HASH_ENGINE_START_SHA256_FAILED);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO,
		HKDF_TESTING_EXPAND_INFO_LEN, key, sizeof (key));
	CuAssertIntEquals (test, HASH_ENGINE_START_SHA256_FAILED, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_clear_prk (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;
	uint8_t key[SHA256_HASH_LENGTH];
	uint8_t zero[HASH_MAX_HASH_LEN] = {0};

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.clear_prk (&hkdf.test.base);
	CuAssertIntEquals (test, 0, status);

	/* Need to inspect the internal state to prove the PRK has been zeroized. */
	status = testing_validate_array (zero, &hkdf.state.prk, sizeof (hkdf.state.prk));
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO,
		HKDF_TESTING_EXPAND_INFO_LEN, key, sizeof (key));
	CuAssertIntEquals (test, HKDF_NO_PRK_AVAILABLE, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_clear_prk_no_extract (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.clear_prk (&hkdf.test.base);
	CuAssertIntEquals (test, 0, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_clear_prk_static_init (CuTest *test)
{
	struct hkdf_testing hkdf = {
		.test = hkdf_static_init (&hkdf.state, &hkdf.hash.base)
	};
	int status;
	uint8_t key[SHA256_HASH_LENGTH];
	uint8_t zero[HASH_MAX_HASH_LEN] = {0};

	TEST_START;

	hkdf_testing_init_static (test, &hkdf);

	status = hkdf.test.base.extract (&hkdf.test.base, HASH_TYPE_SHA256, HKDF_TESTING_EXTRACT_IKM,
		HKDF_TESTING_EXTRACT_IKM_LEN, HKDF_TESTING_EXTRACT_SALT, HKDF_TESTING_EXTRACT_SALT_LEN);
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.clear_prk (&hkdf.test.base);
	CuAssertIntEquals (test, 0, status);

	/* Need to inspect the internal state to prove the PRK has been zeroized. */
	status = testing_validate_array (zero, &hkdf.state.prk, sizeof (hkdf.state.prk));
	CuAssertIntEquals (test, 0, status);

	status = hkdf.test.base.expand (&hkdf.test.base, HKDF_TESTING_EXPAND_INFO,
		HKDF_TESTING_EXPAND_INFO_LEN, key, sizeof (key));
	CuAssertIntEquals (test, HKDF_NO_PRK_AVAILABLE, status);

	hkdf_testing_release (test, &hkdf);
}

static void hkdf_test_clear_prk_null (CuTest *test)
{
	struct hkdf_testing hkdf;
	int status;

	TEST_START;

	hkdf_testing_init (test, &hkdf);

	status = hkdf.test.base.clear_prk (NULL);
	CuAssertIntEquals (test, HKDF_INVALID_ARGUMENT, status);

	hkdf_testing_release (test, &hkdf);
}


// *INDENT-OFF*
TEST_SUITE_START (hkdf);

TEST (hkdf_test_init);
TEST (hkdf_test_init_null);
TEST (hkdf_test_static_init);
TEST (hkdf_test_static_init_null);
TEST (hkdf_test_release_null);
TEST (hkdf_test_extract_sha256);
TEST (hkdf_test_extract_sha256_long_ikm);
TEST (hkdf_test_extract_sha256_zero_length_salt);
TEST (hkdf_test_extract_sha256_no_salt_provided);
#ifdef HASH_ENABLE_SHA1
TEST (hkdf_test_extract_sha1);
TEST (hkdf_test_extract_sha1_long_ikm);
TEST (hkdf_test_extract_sha1_zero_length_salt);
TEST (hkdf_test_extract_sha1_no_salt_provided);
#endif
TEST (hkdf_test_extract_multiple_calls);
#ifdef HASH_ENABLE_SHA1
TEST (hkdf_test_extract_multiple_calls_different_hash_algorithms);
#endif
TEST (hkdf_test_extract_static_init);
TEST (hkdf_test_extract_null);
TEST (hkdf_test_extract_unknown_hash_algorithm);
TEST (hkdf_test_extract_hmac_error);
TEST (hkdf_test_expand_sha256_hash_length_key);
TEST (hkdf_test_expand_sha256_less_than_hash_length_key);
TEST (hkdf_test_expand_sha256_more_than_hash_length_key);
TEST (hkdf_test_expand_sha256_long_ikm);
TEST (hkdf_test_expand_sha256_no_info);
#ifdef HASH_ENABLE_SHA1
TEST (hkdf_test_expand_sha1_hash_length_key);
TEST (hkdf_test_expand_sha1_less_than_hash_length_key);
TEST (hkdf_test_expand_sha1_more_than_hash_length_key);
TEST (hkdf_test_expand_sha1_long_ikm);
TEST (hkdf_test_expand_sha1_no_info);
TEST (hkdf_test_expand_sha1_no_salt_provided);
#endif
TEST (hkdf_test_expand_static_init);
TEST (hkdf_test_expand_null);
TEST (hkdf_test_expand_no_extract);
TEST (hkdf_test_expand_no_extract_static_init);
TEST (hkdf_test_expand_unknown_hash);
TEST (hkdf_test_expand_after_extract_failure);
TEST (hkdf_test_expand_after_extract_failure_after_extract_success);
TEST (hkdf_test_expand_hmac_error);
TEST (hkdf_test_clear_prk);
TEST (hkdf_test_clear_prk_no_extract);
TEST (hkdf_test_clear_prk_static_init);
TEST (hkdf_test_clear_prk_null);

TEST_SUITE_END;
// *INDENT-ON*
