// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef IDE_DRIVER_OBSERVER_H_
#define IDE_DRIVER_OBSERVER_H_

#include "status/module_id.h"


/**
 * Structure to hold the key set and direction for IDE driver notifications.
 */
struct ide_driver_observer_key_set {
	uint8_t stream_id;		/**< The stream ID for the key set. */
	uint8_t key_set;		/**< The key set that was stopped. */
	bool tx_key;			/**< Flag indicating if the key set is for TX (true) or RX (false). */
	uint8_t substream_id;	/**< The substream ID for the key set. */
};

/**
 * Interface for notifying observers of IDE driver events.  Unwanted event notifications will be set
 * to null.
 */
struct ide_driver_observer {
	/**
	 * Notification that an IDE K_SET_STOP has been processed.
	 *
	 * Arguments passed with the notification will never be null.
	 *
	 * @param observer The observer instance being notified.
	 * @param key_set Structure indicating the key set and direction which was stopped.
	 */
	void (*on_set_stop) (const struct ide_driver_observer *observer,
		struct ide_driver_observer_key_set *key_set);
};


#define	IDE_DRIVER_OBSERVER_ERROR(code)	ROT_ERROR (ROT_MODULE_IDE_DRIVER_OBSERVER, code)

/**
 * Error codes that can be generated by an IDE driver observer.
 */
enum {
	IDE_DRIVER_OBSERVER_INVALID_ARGUMENT = IDE_DRIVER_OBSERVER_ERROR (0x00),	/**< Input parameter is null or not valid. */
	IDE_DRIVER_OBSERVER_NO_MEMORY = IDE_DRIVER_OBSERVER_ERROR (0x01),			/**< Memory allocation failed. */
};


#endif	/* IDE_DRIVER_OBSERVER_H_ */
